rizonesoft/Notepad3

- scintilla/deelx/DeelxRegexSearch.cxx
- src/Helpers.c
- src/Helpers.h
- src/Notepad3.c
- fixed: broken Ctrl-Q (toggle line comments)
- remember more settings/checksboxes for “Find text” dialog between sessions (.ini-file persistence of (open) dialog)
- DeelX RegexSearch:  remove EXTENDED mode - that disables white space ignore and '#' as line comment (expexted/convenient behaviour)
-- that fixes also the "Alt-W" (remove trailing spaces) issue on selection only
- fixing ".LOG-feature" of Notepad : ".LOG" recognition must be case sensitive
> minor fixes (initiated by some reportes issues)

- src/Notepad3.c
- src/Styles.c
or preserves selection mode (extends selection on caret movement)
-> need to send SCI_CANCEL at the end of restored selection, instead of previous mode
> + fix:  undo destructive operation on selection (rectangle) does not restore selection

- src/Edit.c
- src/Notepad3.c
- src/Notepad3.h
- #79  : Paste from clipboard to ANSI code page: unnecessary switching encoding to UTF-8
- #90  : FILE status becomes [MODIFIED] when doing CONTROL+A ie to select ALL
> fixing some issues

- src/Edit.c
- src/Notepad3.c
Addressing issues:
#32 (Feature request: copy/cut lines with ctrl-c/x when no selection)
#97 (Conversion of encoding is broken in 2.17.923.505 ?)
#102 (Wrong text conversion pasting Unicode text from clipboard into current ANSI code-page)
> Bug fixes 1004+

- src/Dialogs.c
- src/Dlapi.c
- src/Helpers.c
- src/Helpers.h
- src/Notepad3.c
+ fix: crash in Favorites management 
(release version only, debug version didn't crash - so hard to find)
+ small code refactoring (replacing deprecated methods)
Addressed issue (?):  reported at:
https://www.rizonesoft.com/downloads/notepad3/#comment-39463
> fixes crash in Favorites Management

- src/Edit.c
- src/Edit.h
+ fix: issue #173 - regex/wildcard search: replacement string not used if "Check All Occurrences" is active
> fixing replacement issue in case of active "Check All Occ" feature

- src/Notepad3.c
- src/SciCall.h
- src/Styles.c
- Using of DirectWrite technology must be enabled explicitly now.
- Buffered drawing has been disabled, modern platforms are doing this internally
> Reverting default for Scintilla's DirectWrite technology

- src/Styles.c
- src/Styles.h
+ fix: setting "Default Font..." will clear current lexer's default font - inherits global default font then
+ minor code cleanup
Addressed issue: https://github.com/rizonesoft/Notepad3/issues/236#issuecomment-352224348
> Bugfixes 1217

- src/Styles.c
+ fix: new Font selection feature:  2nd Default Font not supported completely
Addressed issue: https://github.com/rizonesoft/Notepad3/issues/236#issuecomment-353473954
> Fixing font selection support of 2nd Default Style

- src/Notepad3.c
- src/Notepad3.h
+ refactor: move hard-coded hyperlink text from source code file to header file
+ fix: setting/changing encryption pass-phrase did not trigger "file modified" flag
Addressed issue:  https://github.com/rizonesoft/Notepad3/issues/241#issuecomment-353543794
> Fix: setting/changing passphrase did not set file modified flag

- src/Dialogs.c
- src/Edit.c
- src/Helpers.h
- src/Notepad3.c
- src/Print.cpp
- src/Styles.c
+ refactoring: prefix (g_) for global visible objects
+ fix: problem with 1st vs. 2nd Default Text Scheme selection
+ add: better title of Font Selection dialog
Addressed issue: https://github.com/rizonesoft/Notepad3/issues/236#issuecomment-353674389
> Fix: Inconsistency 1st vs. 2nd Default Text Font selection

- src/Notepad3.c
- src/Styles.c
+ fix: set standard lexer (Default Text) on new (empty) files
Addressed Issue:  #252
> Fix: Use Standard Lexer on new (empty) files

- src/Edit.c
- src/Edit.h
- src/Notepad3.c
- src/SciCall.h
+ fix: protect SCI target transactions by a guard to break recursion Mark Occurrences caused by ChangeNotification events
> Bugfixes 0110

- src/Styles.c
+ fix: selection of 1st or 2nd standard lexer (Default Text) based on Use2ndStandard flag
> Fix regarding selection of 1st or 2nd Standard Lexer

- minipath/minipath.vcxproj
- np3encrypt/np3encrypt.vcxproj
- scintilla/Scintilla.vcxproj
- src/Notepad3.vcxproj
+ chg: revert compiler optimization settings back to "Maximize Speed (/O2)" combine with 2nd opt. "Favor Size or Speed: Favor small code (/Os)"
Related issue: https://github.com/rizonesoft/Notepad3/issues/368#issuecomment-367237174
> Revert compiler optimization settings to favor size

- src/Dialogs.c
- src/Edit.c
+ fix: remember incremental search string (if any match) on closing find-repl. dialog
+ fix: sorting lines: merge empty (zero-length) lines
> Dev MultiLingual (minor fixes)

- src/Edit.c
- src/Notepad3.c
- src/SciCall.h
+ fix: ensure caret/selection visibility in case of word-wrap toggle
> Ensure caret/selection visibility

- src/Helpers.h
+ fix (suggested by @zufuliu): using lroundf() instead of "incorrect" (int)(F+0.5f) idiom.
> Rounding float to int fix

- src/Styles.c
In C, consecutive string literals are concatenated with no spaces
between them. Hence, before this commit, the token string contained
`uintmax_t__int16` which was apparently a typo.
> src/Styles.c: Make C lexer recognize `uintmax_t` and `__int16`.

- scintilla/win32/ScintillaWin.cxx
- src/Notepad3.c
+ fix: send Ctrl+Mouse-Wheel zooming to parent window (NP3) too
> Add missing notification on Ctrl+Mouse-Wheel zooming

- src/Dialogs.c
- src/Edit.c
- src/Notepad3.c
+ fix: UTF-8 encoding detection: allow less reliable CED-Analysis of UTF-8 as soft-hint => prefer UTF-8
> Relaxed UTF-8 encoding validation conditions

- src/Dialogs.c
- src/Notepad3.c
+ fix: load resources before displaying command-line-help dialog
+ fix: center dialog in case of missing parent window
> Small fixes for command-line-help dialog

- doc/KeyboardShortcuts.txt
The correct one is Ctrl+Alt+H, not Alt+H
> Wrong shortcut to Recent file (History)

- doc/KeyboardShortcuts.txt
The correct one is Alt+F9, not F9
> Wrong shortcut to Favorites

- language/np3_af_za/strings_af_za.rc
- language/np3_be_by/strings_be_by.rc
- language/np3_de_de/strings_de_de.rc
- language/np3_en_gb/strings_en_gb.rc
- language/np3_en_us/strings_en_us.rc
- language/np3_es_es/strings_es_es.rc
- language/np3_fr_fr/strings_fr_fr.rc
- language/np3_hu_hu/strings_hu_hu.rc
- language/np3_it_it/strings_it_it.rc
- language/np3_ja_jp/strings_ja_jp.rc
- language/np3_ko_kr/strings_ko_kr.rc
- language/np3_nl_nl/strings_nl_nl.rc
- language/np3_pt_br/strings_pt_br.rc
- language/np3_ru_ru/strings_ru_ru.rc
- language/np3_zh_cn/strings_zh_cn.rc
- Suppress " Modern" because it"s relative to "Sort(ing)" and not to "Spain"
> MUI - Translation of Languages in es-es

- src/Notepad3.c
+ chg: in case of (partial) selection, copy only selection instead of complete hyperlink (issue #1296)
> Don't copy complete Hyperlink, if only parts are selected

- scintilla/win32/ScintillaWin.cxx
EDIT: This is my second attempt to add the pull request. I closed my first attempt, because the code was wrong. It works perfectly now!
This is a small pull request to add a simple feature:
Hold down the right mouse button and scroll with the mouse wheel to cycle through the change history of the document. It works fast and well. Hopefully you'll accept the feature, as I think it's really cool!
This was a test of my ability to read through the Notepad3 code for the first time. I spent hours learning the code base today and learning my way around VS2019 Community edition. Please be gentle.. This is my first pull request ever!
I wanted to make a fun poweruser feature that was very low impact, just a few lines of code.
> Update ScintillaWin.cxx (Hold Right Mouse Button and Scroll Mouse Wheel to Cycle Through Undo History Forward and Backwards)

- Build/Changes.txt
- language/np3_de_de/dialogs_de_de.rc
- language/np3_en_gb/dialogs_en_gb.rc
- language/np3_en_us/dialogs_en_us.rc
- src/Dialogs.c
- src/Edit.c
@hpwamr : Wording changed for en-US,en-GB,de-DE - please change all remaining languages accordingly.
> Encoding (Default) Settings dialog: use positive wording for all items

- Build/Notepad3.ini
- src/Config/Config.cpp
lower confidence level for UCHARDET and use system's code-page as detection fallback by default)
> Relax UTF-8 orientation

- src/StyleLexers/styleLexAHKL.c
Source: https://github.com/ahkscript/AutoHotkey-Editors (Directives.txt, Commands.txt, Keywords.txt, Functions.txt, Variables.txt, Keys.txt resp.)
> Apply Start Case to AutoHotkey Lexer

- Build/Notepad3.ini
- src/Config/Config.cpp
- src/Notepad3.c
- src/TypeDefs.h
- src/Version.h
to disable VS's Ctrl+X behavior on empty selection.
VS Compiler version update (VS 16.3.0, VC 1923)
> Add hidden option ([Settings2] NoCutLineOnEmptySelection)

- language/np3_zh_cn/menu_zh_cn.rc
Replace the verb with an adverb in **No highlight**. This mistake has been there long ago. :joy:
>  language/np3_zh_cn: Update translation for zh_CN.

- minipath/language/mp_es_es/resource.h
- This error is detected with the test of new "rcdll.dll"
> +Fix - Corrected the encoding to ANSI (remove utf-8 Signature)

- language/np3_ja_jp/dialogs_ja_jp.rc
- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ja_jp/strings_ja_jp.rc
Translation for new huge files. And, Adjusted overall.
I noticed there. The top position of "X Time" is a little higher. We should move this down a little.
In `dialogs.rc` :
```
CAPTION "Insert HTML/XML Tag"
...
FONT 8, "MS Shell Dlg", 0, 0, 0x0
LTEXT           "X Times",IDC_STATIC,148,50,24,8
```
> ja_jp: huge file, adjust

- src/StyleLexers/styleLexVHDL.c
- src/Styles.c
…  (crash of VHDL lexer)
@hpwamr : There wa an empty keyword list ("") missing for `VHDL` (`StyleLexers/styleLexVHDL.c`).
Maybe from the Keyword List refactoring.
Please check if the keywords still fit to the Type (compare to `Scintilla/lexers/LexVHDL.cxx`, lines 64-70)
If Notepad3 is compiled in Debug mode (instead of Release mode), you will be informed (debug assertion) if other lexers have a missing entry ...
> Avoid crash on too few fields for lexer's keyword lists

- scintilla/win32/ScintillaWin.cxx
Canceling behavior of Japanese IME via https://github.com/zufuliu/notepad2/commit/f75470d5be2dd27c8e05d87adf19fbf7197c87c0. 
Zufuliu fixed it. I want to report to Scinttila. But, Debugging Scintilla is difficult for me. However, this code fixes the behavior of the IME. If PL is not good, I will talk in the ISSUE.
Other languages are probably not affected. I tried it briefly.
Previous reports: https://github.com/rizonesoft/Notepad3/issues/632#issuecomment-416623554
> ScintillaWin: Canceling behavior of Japanese IME

- language/np3_ja_jp/strings_ja_jp.rc
- scintilla/win32/ScintillaWin.cxx
Translation, and new fix of Scintilla beta: [Handle Japanese IME input when both GCS_COMPSTR and GCS_RESULTSTR set](https://sourceforge.net/p/scintilla/code/ci/92d3ec5798695db9da797028ea7b3cc701b3270d/). (Formal code of previous IME fix)
> Translation, and new fix of Scintilla beta

- grepWinNP3/translationsNP3/日本語 （日本） [ja-JP].lang
Delete single unnecessary space.
> grepWinNP3 JP: typo

- grepWinNP3/translationsNP3/日本語 （日本） [ja-JP].lang
I understand "Capture". #2516 has already been merged.
Assign the "Replace with" shortcut ```R``` by the previous translator Tilt. But, this was changed to ```H``` because of the conflict.
> Translation >Japanese : 2020/Jul, grepWinNP3 Capture 2ed

- grepWinNP3/translationsNP3/한국어 (대한민국) [ko-KR].lang
This PR adds in new translations, as well as some minor typo fixes.
Couldn't understand the `Capture Search` feature. Therefore the translations are very rough for two strings regarding the feature.
> ko-KR translations and typo fix for grepWinNP3.

- grepWinNP3/default.build
- grepWinNP3/src/SearchDlg.cpp
- grepWinNP3/src/SearchDlg.h
- grepWinNP3/src/last/version.h
- src/Dialogs.c
- src/Dialogs.h
@hpwamr :
If testing Dialogbox UI Layaut for Asian languages, please keep in mind, that not all font faces may be available on your system.
```
switch (PRIMARYLANGID(lang)) {
default:
case LANG_ENGLISH:
font   = L"Segoe UI";
*wSize = 9;
break;
case LANG_CHINESE:
font   = IsChineseTraditionalSubLang(subLang) ? L"Microsoft JhengHei UI" : L"Microsoft YaHei UI";
*wSize = 9;
break;
case LANG_JAPANESE:
font   = L"Meiryo UI";
*wSize = 9;
break;
case LANG_KOREAN:
font   = L"Malgun Gothic";
*wSize = 9;
break;
}
```
> Use optimized Asian UI fonts for dialog boxes

- src/Edit.c
- src/Helpers.h
- src/Notepad3.c
+ fix: TinyExpr: inline evaluation on active option only
+ fix: TinyExpr: allow rh equal and questionmark
+ fix: TinyExpr: newline after evaluation by '=<ENTER>'
>  Missed to stage main changes in previous commit

- src/Edit.c
- src/Notepad3.c
(Native Scintilla-based SCI_LINECUT not working on multi-selection  - better using explicit line marking for this use-case)
> Fix: disable Copy/Cut complete lines on partial multi-selection or rectangular-selection

- scintilla/include/Sci_Position.h
> Sci_PositionCR type reverted to long for Win32 compatibility reasons

- src/Edit.c
- src/Edit.h
try to solve issue #3013.
@hpwamr : Please test also possible side-effects, e.g.:
- replacing "zero-length-matches" by e.g. line-begin (`^`) or line-end (`$`) pattern
(using "`Overlapping search`" may produce unexpected results, e.g infinite loops, or replacing all:
- replacing all '$' in "123456\r\n" with '7' (using option `Overlapping search`) will repeatedly append '7' at the end until NP3 
crashes, cause next search starts right before line-end. Switch OFF `Overlapping search` to proceed beyond the line-end.
- replacing all '^\d' in "123456\r\n" with ''(empty/nothing) (using option `Overlapping search`) will delete all numbers,
because after deleting (=replacing with empty) one number at the  line-begin results in next number at line-begin.
Switch OFF `Overlapping search` to proceed …
> Fix Multi-Replace using RegExpr and Group-References

- language/np3_ja_jp/strings_ja_jp.rc
Hi!
It has already been translated in the original GrepWin.
There is an untranslated.
IDS_MUI_WRAPSEARCH_FWD seems not to be implemented yet:
265&266 IDS_MUI_WRAPSEARCH_FWD & IDS_MUI_WRAPSEARCH_BCK
> Translation >Japanese : 2021/Feb LOCALE_DATEFMT

- src/Config/Config.cpp
- src/Dialogs.c
- src/Edit.c
- src/Notepad3.c
- src/Resample.c
- src/TypeDefs.h
- src/tinyexpr/tinyexpr.c
This will speed-up handling of large selections.
(Huge Files: bigger than `[Settings2] FileLoadWarningMB`)
ref. issue #3075
> Statusbar Selection-Info: switch to byte (instead of character) counting for huge files   

- lexilla/Lexilla.vcxproj
- scintilla/Scintilla.vcxproj
- src/Dialogs.c
- src/Dialogs.h
- src/Edit.c
- src/Helpers.c
- src/Helpers.h
- src/Notepad3.vcxproj
ref. issue #3107
@hpwamr : Please test thoroughly, cause of changes at the core of the Find/Repl dialog.
Major Points for F/R-Dialog here are:
- Mark Occurrences On/Off 
- Focused View toggle adding marker
- Searching while typing / selecting older pattern
- Switching to editor, edit, move caret and back to F/R-Dialog (re-activation)
- Cooperation of Dialog with (Ctrl+F3 searching with and w/o F/R-Dialog)
- maybe more I forgot here ... 😅
> Find/Repl dialog - refactoring and minor fixes

- language/np3_en_us/menu_en_us.rc
- src/Edit.c
- src/Notepad3.c
+ chg: Menu (en-US) move line/stream comment items to Edit->Selection top
+ fix: JSON Lexer has comments enabled now
+ chg: Simple Line Comment Toggle handles each line separately
(Line Edit after toggle will still set mode of 1st line == former behavior)
> Change simple Line Comment Toggle behavior & move menu entry

- src/Edit.c
keep position of selection end.
ref. issue #3115
> Toggle comment on empty selection at insertion point

- src/Notepad3.c
- src/SciCall.h
- src/Styles.c
... if line-number marginwidth set to 0 (so use 1 instead)
ref. issue #3337
> Workaround Scintilla text-rendering bug

- grepWinNP3/grepWinNP3.vcxproj
- grepWinNP3/grepWinNP3.vcxproj.filters
- grepWinNP3/src/SearchDlg.cpp
- lexilla/Lexilla.vcxproj
- lexilla/lexers_x/LexCSV.cxx
- lexilla/lexers_x/LexTOML.cxx
- lexilla/lexers_x/LexerUtils.h
- scintilla/Scintilla.vcxproj
- scintilla/oniguruma/scintilla/OnigurumaRegExEngine.cxx
- scintilla/oniguruma/src/config.h
+ chg: enable compiler warnings level 4 and issue "Warnings as Errors" (for Lexilla, Scintilla, grepWinNP3)
> Fix grepWinNP3: fix compiler warning Release Win32

- src/Styles.c
+ fix: another bug retrieving Font SIze for Common Default vs. Lexer Specific
ref. issue #3344
> Changed: prefer Cascadia Code font over Consolas for default if installed (ligatures)

- lexilla/lexers_x/LexMarkdown.cxx
> Fixing "infinite" loop in Markdown Lexer

- language/np3_af_za/strings_af_za.rc
- language/np3_be_by/strings_be_by.rc
- language/np3_de_de/strings_de_de.rc
- language/np3_el_gr/strings_el_gr.rc
- language/np3_en_gb/strings_en_gb.rc
- language/np3_en_us/strings_en_us.rc
- language/np3_es_419/strings_es_419.rc
- language/np3_es_es/strings_es_es.rc
- language/np3_fr_fr/strings_fr_fr.rc
- language/np3_hi_in/strings_hi_in.rc
- language/np3_hu_hu/strings_hu_hu.rc
- language/np3_id_id/strings_id_id.rc
- language/np3_it_it/strings_it_it.rc
- language/np3_ja_jp/strings_ja_jp.rc
- language/np3_ko_kr/strings_ko_kr.rc
- language/np3_nl_nl/strings_nl_nl.rc
- language/np3_pt_br/strings_pt_br.rc
- language/np3_pt_pt/strings_pt_pt.rc
- language/np3_ru_ru/strings_ru_ru.rc
- language/np3_sk_sk/strings_sk_sk.rc
- language/np3_sv_se/strings_sv_se.rc
- language/np3_tr_tr/strings_tr_tr.rc
- language/np3_vi_vn/strings_vi_vn.rc
- language/np3_zh_cn/strings_zh_cn.rc
- language/np3_zh_tw/strings_zh_tw.rc
- src/Config/Config.cpp
- src/Edit.c
- src/Helpers.c
+chg: limit file size: 2GB (Until WideCharToMultiByte() / MultiByteToWideChar() INT32_MAX issues are clarified)
ref. issue #3656.
>  Goto-Dialog: digit grouping of line/column numbers

- Build/Notepad3.ini
- src/Config/Config.cpp
- src/Notepad3.c
- src/TypeDefs.h
+chg: allow [Settings2] "FileCheckInverval" to be zero(0), means no active file change polling
+chg: remove deprecated "AutoReloadTimeout"
ref. issue #3516
> Disable actively file change polling - rely on directory change notification by default

- grepWinNP3/translationsNP3/Nederlands (Nederland) [nl-NL].lang
First major overhaul of the Dutch translation.
I hope it all fits, because like German, Dutch tends to use more space than English
> Update Nederlands (Nederland) [nl-NL].lang

- language/np3_zh_cn/menu_zh_cn.rc
- language/np3_zh_tw/menu_zh_tw.rc
The original translation "切换聚焦" is confusing, similar to "Switch focus" or "Toggle focused".
The new translation means Focus mode (engrossing mode), it is used by iOS and more.
Ref: https://support.apple.com/en-us/HT212608, https://support.apple.com/zh-cn/HT212608, https://support.apple.com/zh-tw/HT212608.
> Changed IDM_VIEW_TOGGLE_VIEW translation

- src/Edit.c
> RegEx Scanner: don't allow XML tagging brackets as part of Hyperlink text

- scintilla/win32/ScintillaWin.cxx
Logitech horizontal mouse wheel not working in Notepad3 with Logitech Options installed.
This is a common problem caused by crooked Logitech software.
This problem is consistently repeated in other text editors based on Scintilla, and also in standard Delphi VCL components.
If you follow the documentation and return in response to `WM_MOUSEHWHEEL` `0`, then Logitech Options (or Windows) stops sending `WM_MOUSEHWHEEL` altogether, the scrollbar loses its style and moves without any messages (which can be processed in WndProc). If you return `1`, then magically everything starts working correctly. There is another `return 0` above in the code, but according to my tests, it does not lead to this problem.
Closes #3976.
> Fix horizontal mouse wheel with Logitech Options utility

- src/Styles.c
ref. issue https://github.com/rizonesoft/Notepad3/issues/4020
> +fix: using by error 'Segoe UI'' as default for pure 'Text File' scheme

- language/np3_de_de/menu_de_de.rc
- language/np3_de_de/strings_de_de.rc
- language/np3_en_us/menu_en_us.rc
- language/np3_en_us/strings_en_us.rc
- src/Notepad3.c
ref. issues: #3927, #3890, #4062
@hpwamr :
Please see changes to `IDM_VIEW_READONLY` (Menu: View -> Edit + Separator) and changed text for `IDS_MUI_DOCUMENT_READONLY` (inverse meaning for quiet ignore dialog popup - vice versa makes no sense for this option)
> Decouple read-only file attribute from read-only document view mode

- language/common_res.h
- language/np3_de_de/dialogs_de_de.rc
- language/np3_en_us/dialogs_en_us.rc
- src/Config/Config.cpp
- src/Dialogs.c
- src/Dialogs.h
- src/Edit.c
- src/Notepad3.c
- src/SciCall.h
- src/crypto/crypto.c
+chg: use deprecated SCI_FINDTEXT to workaround crash on new (Sci v5.2.3) SCI_FINDTEXTFULL method.
> Hotfix for crash in SCI_FINDTEXTFULL

- language/np3_de_de/lexer_de_de.rc
- language/np3_el_gr/lexer_el_gr.rc
- language/np3_en_gb/lexer_en_gb.rc
- language/np3_en_us/lexer_en_us.rc
- language/np3_es_es/lexer_es_es.rc
- language/np3_es_mx/lexer_es_mx.rc
- language/np3_fr_fr/lexer_fr_fr.rc
- language/np3_id_id/lexer_id_id.rc
- language/np3_it_it/lexer_it_it.rc
- language/np3_pl_pl/lexer_pl_pl.rc
- language/np3_sk_sk/lexer_sk_sk.rc
- language/np3_vi_vn/lexer_vi_vn.rc
- lexilla/lexers_x/todo_lexers.txt
- src/Helpers.c
- src/Styles.c
> Caret style: allow std caret bar width up to max(20) and define alpha transparency (not below 20)

- grepWinNP3/src/AboutDlg.cpp
This link is accessable from software rather than just code or doc. So I think https is better.
> chore: use https

- language/np3_zh_cn/menu_zh_cn.rc
- language/np3_zh_tw/menu_zh_tw.rc
This new menu element lacks a shortcut. I think `Auto C&lose Brackets` would be good.
> Update translation for zh_CN and zh_TW

- src/Config/Config.cpp
- src/Notepad3.c
- src/TypeDefs.h
(deprecated: Settings2 section)
(cherry picked from commit d5ae772ea5693caba02617069c243c35ac8f2f5b)
> Move DefaultWindowPosition to Window section

- src/Styles.c
(cherry picked from commit cce29646f364c3ae7d93dde71c966ed766b7fa0c)
need to add `charset:3;` to `Scheme::Common Base::Bookmarks and Folding` 
see also issue #4321
> Allow "dotbox" instead of "horiz. line" for folded text

- Build/Changes.txt
> MUI - Fix encoding as "UTF-8 Signature" for Korean INNO Setup localization

- res/StdDarkModeScheme.ini
- src/StyleLexers/styleLexStandard.c
- src/Styles.c
- src/Styles.h
Scheme Config: show Defaults merged with Common Base inherits
> Lexer TEXT using own Default but inheriting from Common Base

- scintilla/Scintilla.vcxproj
- scintilla/Scintilla.vcxproj.filters
- scintilla/oniguruma/scintilla/OnigurumaRegExEngine.cxx
- scintilla/oniguruma/src/ascii.c
- scintilla/oniguruma/src/make_unicode_property_data.py
- scintilla/oniguruma/src/oniguruma.h
- scintilla/oniguruma/src/regcomp.c
- scintilla/oniguruma/src/regenc.c
- scintilla/oniguruma/src/regexec.c
- scintilla/oniguruma/src/regext.c
- scintilla/oniguruma/src/regparse.c
- scintilla/oniguruma/src/regposix.c
- src/Edit.c
- src/Notepad3.c
(in case of EOL or indent correction)
ref. issue #4630
RegExpr Search enhancements (ref. issue #4596)
> Fix: don't reset "dirty flag" after file loading

- src/Notepad3.c
- src/SciCall.h
... if it is part of rectangular selection
ref. issue #4645
> Fix: Shift+Alt+Click on Hyperlink should not fire Hyperlink action

- language/np3_ja_jp/strings_ja_jp.rc
It is returned to "&Factory Reset" in this PL. https://github.com/rizonesoft/Notepad3/commit/4091eaa031253fea8085765b92304b8433e51f02
But it is "&Factory Reset" from before in '''strings_en_us.rc'''.
However Japanese translation has been changed.
> Translation >Japanese : 2023/May Missing

- scintilla/win32/ScintillaWin.cxx
This change makes horizontal scrolling using touchpad gestures or mice with a scroll left/right feature match other Windows applications. The behavior prior to this commit is backwards when compared to the standard.
This change is intended to address issue https://github.com/rizonesoft/Notepad3/issues/5020
> Fix horizontal mouse wheel scroll direction

- src/Edit.c
- src/SciCall.h
- now behaves the same as line selected including line-breaks
ref. issue #5056
> Change ndentation in case of complete line selected

- src/Notepad3.c
> Fix Tinyexpr: integer values always shown in abs() format

- Build/Notepad3.ini
- src/Config/Config.cpp
- src/Notepad3.c
- src/TypeDefs.h
option to get old behavior: `[Settings2] SubWrappedLineSelectOnMarginClick=true`
ref. issue #5024
> Change line selection on margin click from sub-line to whole-line

- src/Dialogs.c
- src/Dialogs.h
- src/Edit.c
- src/Notepad3.c
- src/Styles.c
- src/crypto/crypto.c
> Fix: center popup dialogs and show current line on word-wrap toggle

- src/Dialogs.c
- src/Dialogs.h
- src/Edit.c
- src/Notepad3.c
- src/Styles.c
- src/crypto/crypto.c
> Fix: center dialog if window is maximized

- src/Notepad3.c
It's very disrupting, especially when tail mode or auto reload has been turned on.
> fix: Do not bring main window to foreground upon file change

- Build/Changes.txt
- Fix: Language files missing in Notepad3 portable version
> MUI - Commit before release build "Notepad3 6.24.1219.2 rc3"

- grepWinNP3/src/SearchDlg.cpp
- src/Dialogs.c
- src/Notepad3.c
- src/TypeDefs.h
+chg: FileChandedIndicator and FileDeletedIndicator may be 30 chars long
+fix: vc143 compiler issue for grepWin
ref. issue #5325
> FileChandedIndicator and FileDeletedIndicator may be 30 chars long

- scintilla/scripts/FileGenerator.py
This small PR resolves the annoying regex library warnings showing starting Python3.11:
```python
/tmp/notepad3/scintilla/scripts/FileGenerator.py:184: DeprecationWarning: 'count' is passed as positional argument
```
> Resolve regex library warnings
