rizonesoft/Notepad3

- crypto/crypto.c
- crypto/rijndael-alg-fst.c
- crypto/rijndael-alg-fst.h
- src/Edit.c
and fixing crypto issue "passphrase longer than plaintext"
> fixing 64bit issue XhmikosR/notepad2-mod#37

- src/Edit.c
> clean-code solution (instead of "magic numbers") 

- src/Notepad3.c
> + fixed: "file modified" flag not set on Ctrl+X actions

- src/Notepad3.c
> + remember window position in case of "relaunch elevated"

- src/Edit.c
+ fixed bug:  open find dialog the first time (new NP3 instance) 
while clipboard is empty, NP3 crashes
(try to LocalFree() static allocated memory)
> Solving issue #76

- Readme.txt
> Update Readme.txt: Secure Link

- distrib/Changes.txt
Huwayy, I got to help another repo ;) :D :D
> Made some corrections to build 505 change log (spelling, grammar, etc)

- distrib/Changes.txt
lol really minor spelling correction...
> Made corrections to build 518 change log (spelling, Oktober -> October).

- src/Edit.c
- src/Edit.h
- src/Notepad3.c
Addressed issue:
+ #24 (block selection)
! Changed behavior: 
allow "Virtual (Space) Rectangular Selection" 
also allows moving Caret into virtual space (beyond line end))
> Bugfixes 1005+

- np3portableapp/build_np3portableapp.cmd
- src/Edit.c
- src/Edit.h
- src/Notepad3.c
Addressed issue(s):
#113 (current column indicator)
> Bugfixes 1010

- src/Edit.c
- src/Edit.h
- src/Helpers.c
- src/Helpers.h
- src/Notepad3.c
- src/Styles.c
... up to first hundreds of Bookmarks (depending on line number digits) - should be enough
>  New feature: auto remember bookmarks in recent file history

- minipath/minipath.vcxproj
- minipath/src/version.h
- np3encrypt/np3encrypt.vcxproj
- scintilla/Scintilla.vcxproj
- src/Notepad3.vcxproj
reported in release build process
> - fix: corrections to .vcproj settings inconsistencies

- src/Edit.c
+ fix bug: find next changed to cover zero-length matches moved to far to get next match
> Last Minute bug-fixes  :-/

- minipath/src/Helpers.c
+ feature: additionally show full path to current directory in windows title
> MiniPath:  additionally show full path of current directory in titlebar

- src/Edit.c
- src/Edit.h
- src/Notepad3.c
+fix: find/replace dialog: mark occurrences: use standard save/restore settings behavior
> Last Minute Fixes

- src/Edit.c
- src/Helpers.c
+fix: HTML character encoding starts with ampersand, not percent char
> URL resp. HTML decoding fix

- src/Edit.c
- src/Notepad3.c
- src/Styles.c
Addressed issue:  https://github.com/rizonesoft/Notepad3/issues/210#issuecomment-350534870
> Hyperlink fixes

- src/Edit.c
- src/Edit.h
- src/Notepad3.c
- src/Notepad3.h
- src/Styles.c
- src/Styles.h
Addressed issue: https://github.com/rizonesoft/Notepad3/issues/210#issuecomment-350859547
> Hyperlink Hotspot fixes

- src/Dialogs.c
- src/Edit.c
- src/Helpers.c
- src/Helpers.h
- src/Notepad3.c
- src/Print.cpp
- src/SciCall.h
- src/Styles.c
- src/Styles.h
Addressed issues:
#229 
separating "replace selection" from "searching in target" (needed for frequent hyperlink styling)
add "Mark Occurrences" indicator style to scheme config
minor improvements
> Bugfixes 1214 ii

- src/Notepad3.c
- src/Notepad3.rc
+ fix: inconsistencies:  cut,copy,replace,...  main menu and context menu vs. toolbar
Addressed issue: #245
> Fix inconsistencies:  menu (main & context) vs. toolbar

- scintilla/include/Scintilla.h
- scionigmo/OnigmoRegExEngine.cxx
- src/Edit.c
- src/Edit.h
- src/Notepad3.c
- src/Notepad3.rc
- src/Styles.c
- src/resource.h
Addressed issues:
- https://github.com/rizonesoft/Notepad3/issues/254#issuecomment-353725929
- #257 
- #258
> Enhancements 1226

- scintilla/doc/Design.html
- scintilla/doc/ScintillaDoc.html
- scintilla/doc/ScintillaHistory.html
- scintilla/doc/ScintillaRelated.html
- scintilla/lexers/LexVHDL.cxx
- scintilla/src/Catalogue.cxx
- src/Edit.c
- src/Helpers.c
- src/Helpers.h
- src/Notepad3.c
- src/Notepad3.rc
+ revert: to MBCS (UTF-8) byte counting in status bar
+ clean code
Addressed issue: #302
> Fix: correct in-memory encoding/re-coding of text

- src/Edit.c
- src/Edit.h
- src/Notepad3.c
- src/Notepad3.rc
- src/resource.h
> Fix: Join Lines , New: Fuse Lines

- src/Edit.c
- src/Edit.h
- src/Notepad3.c
+ fix: avoid some issues regarding folding, using SCI_SETAUTOMATICFOLD
> Fixing issues around Folding

- src/Edit.c
- src/Edit.h
- src/Notepad3.c
- src/SciCall.h
+ enh: make selection block indentation similar to VisualStudio
> Bugfixes_0129 II

- src/Edit.c
+ fix: Char2Hex: remove limit single byte selection
> Bugfixes 0130

- src/Edit.c
- src/Edit.h
- src/Notepad3.c
- src/Notepad3.h
- src/Notepad3.rc
- src/Styles.c
- src/Version.h
Addressed issues:  #334, #335, #336
> Fixes 0202

- scintilla/Scintilla.vcxproj
- scintilla/Scintilla.vcxproj.filters
- scintilla/lexers/LexRegistry.cxx
- scintilla/src/Catalogue.cxx
- src/Edit.c
- src/Notepad3.c
- src/Notepad3.rc
- src/Styles.c
- src/Styles.h
- chg: `Windows Registry Files` lexer: changed to support Reg-Key styling attribute `eolfilled` (#359)
- new: add `R-Statistics Code` lexer (exists upstream) (#360)
> Lexers and more

- src/Edit.c
+ fix: performance issue: Replace All - delay status update until transaction finished
> HotFix 0222

- src/Edit.c
- src/Notepad3.c
+ fix: avoid deadlock of occurrence marker task scheduler
> Bugfixes 0405

- Build/Changes.txt
There is one large chunk near the end of the changelog file that was prefixed with only -/+ so I left that alone for now...
> Sorted all/most of the change log file.  First go through.

- src/Dialogs.c
- src/Helpers.c
- src/Helpers.h
+ del: remove obsolete GetSystemDPI() usage
> Remove obsolete GetSystemDPI() usage

- src/Edit.c
- src/Notepad3.c
- src/Notepad3.h
+ chg: statusbar: Col and Ch counting according to NP2-mod/zufuliu convention
+ fix: some code cleanup
> Fix: Statusbar Col & Ch counting

- src/Notepad3.c
[Comments are here.](https://github.com/rizonesoft/Notepad3/issues/668#issuecomment-421228283).
> fix:AutoComp on IME Native mode

- .editorconfig
- Notepad3.sln
- src/ChooseFont/ChooseFont.cpp
See:
https://EditorConfig.org
https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2017
> .editorconfig (UTF-8 affine) for VisualStudio editor

- language/np3_de_de/strings_de_de.rc
- src/Dialogs.c
- src/Version.h
+ enh: center cmdln-help dialog in Notepad3 window
+ fix: format of German cmdln-help strings
> Center command line help dialog

- src/ChooseFont/ChooseFont.cpp
- src/Dialogs.c
- src/Styles.c
+ fix: missing titlebar icon for some dialogs
> Set missing title-bar icons

- language/np3_ja_jp/strings_ja_jp.rc
@hpwamr I finished the command line translation. (*^^)v
> Translation >JP :New command line

- src/Edit.c
- src/Notepad3.c
> Bug fixing

- src/Edit.c
+ fix: replace dialog: in case of selection: on "Replace" button pressed, next finding is selected (analog. to empty selection)
> Replace dialog: in case of selection

- language/np3_de_de/strings_de_de.rc
- scionigmo/OnigmoRegExEngine.cxx
- src/Edit.c
+ speed-up RegEx Search & Replace for fixed (const) (non search pattern group referenced) replacement strings
> RegEx Search & Replace speed-up for const replacement strings

- src/Edit.c
- src/Helpers.h
+ fix: wrong detection of Non-Unicode file as Unicode
> Fix Unicode detection (special case)

- ced/ced/CMakeLists.txt
- ced/ced/compact_enc_det/compact_enc_det.cc
- ced/ced/compact_enc_det/compact_enc_det.h
- ced/ced/compact_enc_det/compact_enc_det_hint_code.cc
- ced/ced/util/encodings/encodings.h
- crypto/crypto.c
- src/Dialogs.c
- src/Dlapi.c
- src/Edit.c
- src/Edit.h
- src/Encoding.c
- src/Helpers.c
- src/Notepad3.c
- src/Styles.c
+ upd: current corrections for Compact Encoding Detection (CED by Google)
+ fix: problem with UTF-8 (no BOM) encoding vs. ANSI encoding detection
+ cln: code cleanup
> Update Compact Encoding Detection (CED)

- minipath/src/minipath.c
- src/Dialogs.c
- src/Edit.c
- src/Helpers.c
- src/Helpers.h
- src/Notepad3.c
- src/Styles.c
- src/TypeDefs.h
> Find correct window for "Single File Instance" (re)load

- crypto/crypto.c
- src/Dialogs.c
- src/Edit.c
- src/Helpers.c
- src/Helpers.h
- src/Notepad3.c
- src/Print.cpp
- src/Styles.c
+ chg: write Language change to Settings2 on change
+ chg: prepare resize method for DPI chnage awareness
> Write Language change to Settings2 on change immediately

- language/np3_af_za/menu_af_za.rc
- language/np3_be_by/menu_be_by.rc
- language/np3_de_de/menu_de_de.rc
- language/np3_en_gb/menu_en_gb.rc
- language/np3_en_us/menu_en_us.rc
- language/np3_es_es/menu_es_es.rc
- language/np3_fr_fr/menu_fr_fr.rc
- language/np3_hu_hu/menu_hu_hu.rc
- language/np3_it_it/menu_it_it.rc
- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ko_kr/menu_ko_kr.rc
- language/np3_nl_nl/menu_nl_nl.rc
- language/np3_pt_br/menu_pt_br.rc
- language/np3_ru_ru/menu_ru_ru.rc
- language/np3_zh_cn/menu_zh_cn.rc
- src/Notepad3.c
- src/Notepad3.h
... to toggle through all 3 possible Toolbars (3rd: external load bitmap)
> Change menu item "HighDPI Toolbar" -> "Toggle Toolbar" 

- src/Helpers.h
- src/Notepad3.c
- src/Styles.c
- src/TypeDefs.h
- src/Version.h
> Fix broken toolbar toggle

- language/np3_zh_cn/menu_zh_cn.rc
> MUI - Chinese translation correction about menu_zh_cn.rc

- language/np3_zh_cn/strings_zh_cn.rc
> language/np3_zh_cn: Update translation for zh_CN.

- language/np3_ja_jp/dialogs_ja_jp.rc
- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ja_jp/strings_ja_jp.rc
I could😊
Rest: I can not understand (I can not reproduce in my operation)
in Dialog
"Autodetect Tab or Space Indentation"
in String
"Search environment PATH in case of relative filename"
Memo:
"Inconsistent Indentation"
I do not know the situation that this dialog appears.
> Translation >JP :few rest

- language/np3_ja_jp/strings_ja_jp.rc
> Ja-JP fixed translate

- language/np3_zh_cn/menu_zh_cn.rc
> language/np3_zh_cn: Add translation for 'Mute Message Beeps'.

- src/Edit.c
- src/Edit.h
- src/Notepad3.c
- src/SciCall.h
- src/Styles.c
+ fix: 2nd try to fix the finalize styling issue (Find/Replace dialog: mark occurrences)
> Changes to fix the missing styling issue

- language/np3_hu_hu/dialogs_hu_hu.rc
- language/np3_hu_hu/menu_hu_hu.rc
- language/np3_hu_hu/strings_hu_hu.rc
- small other corrections and typo
> MUI - Correction of codepage to "Windows-1250" for hu-HU

- language/np3_hu_hu/menu_hu_hu.rc
- language/np3_hu_hu/strings_hu_hu.rc
Chasing doctail and other small changes
> Chasing doctail added

- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ja_jp/strings_ja_jp.rc
> Translation >JP :DOCTAIL,CALLTIP,STYLEEDIT

- language/np3_af_za/strings_af_za.rc
- language/np3_be_by/strings_be_by.rc
- language/np3_de_de/strings_de_de.rc
- language/np3_en_gb/strings_en_gb.rc
- language/np3_en_us/strings_en_us.rc
- language/np3_es_es/strings_es_es.rc
- language/np3_fr_fr/strings_fr_fr.rc
- language/np3_hu_hu/strings_hu_hu.rc
- language/np3_it_it/strings_it_it.rc
- language/np3_ja_jp/strings_ja_jp.rc
- language/np3_ko_kr/strings_ko_kr.rc
- language/np3_nl_nl/strings_nl_nl.rc
- language/np3_pl_pl/strings_pl_pl.rc
- language/np3_pt_br/strings_pt_br.rc
- language/np3_ru_ru/strings_ru_ru.rc
- language/np3_zh_cn/strings_zh_cn.rc
- src/Edit.c
- src/Helpers.c
- src/Helpers.h
- src/Notepad3.c
> Fix some format strings for dialog displaying long integers

- language/np3_hu_hu/dialogs_hu_hu.rc
- language/np3_hu_hu/menu_hu_hu.rc
- language/np3_hu_hu/strings_hu_hu.rc
I think now the problematic ő and ű characters may be fixed and I have translated the recently changed lines you notified in your email.
> Fixed accented characters + New translation for changed lines

- language/np3_ja_jp/strings_ja_jp.rc
> Translation >JP :STYLEEDIT_HELP

- language/np3_af_za/menu_af_za.rc
- language/np3_be_by/menu_be_by.rc
- language/np3_en_gb/menu_en_gb.rc
- language/np3_es_es/menu_es_es.rc
- language/np3_fr_fr/menu_fr_fr.rc
- language/np3_hu_hu/menu_hu_hu.rc
- language/np3_it_it/menu_it_it.rc
- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ko_kr/menu_ko_kr.rc
- language/np3_nl_nl/menu_nl_nl.rc
- language/np3_pl_pl/menu_pl_pl.rc
- language/np3_pt_br/menu_pt_br.rc
- language/np3_ru_ru/menu_ru_ru.rc
- language/np3_zh_cn/menu_zh_cn.rc
- Rename "Force Encoding Detection" --> "Recode to UCHARDET Analysis"
> MUI - Rearranging the" Encoding" menu

- language/np3_hu_hu/menu_hu_hu.rc
- minipath/language/mp_hu_hu/strings_hu_hu.rc
New UCHARDET string and other fix
> New string and typo fix

- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ja_jp/strings_ja_jp.rc
I can read Google translation in String.rc. But I optimized.
Menu.rc is become mistranslation. "reload" convert to "rewirite" of Japanese.
> Translation >JP :optimize google translation

- Build/Changes.txt
- language/np3_en_gb/menu_en_gb.rc
- language/np3_en_us/menu_en_us.rc
- language/np3_pt_br/menu_pt_br.rc
- List of @craigo-  https://github.com/rizonesoft/Notepad3/issues/1274#issuecomment-498527005
> Change Hotkey for Window submenu "View"

- src/Dialogs.c
while trying to write to read-only file.
> Fix wrong error message for error dialog box 

- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ja_jp/strings_ja_jp.rc
> Translation >JP :Appearance

- language/np3_hu_hu/dialogs_hu_hu.rc
I made some shortenings of texts but I cannot do all of them.
> Some strings shortened

- language/np3_hu_hu/dialogs_hu_hu.rc
It would look better on the interface.
(Now I have synced my repo before making changes...)
> Changing  Jump to {Search/Replace} to shorter text

- language/np3_zh_cn/lexer_zh_cn.rc
- language/np3_zh_cn/menu_zh_cn.rc
- language/np3_zh_cn/strings_zh_cn.rc
> language/np3_zh_cn/: Update translation for zh_CN.

- Build/Changes.txt
- src/StyleLexers/styleLexCOFFEESCRIPT.c
- src/StyleLexers/styleLexCONF.c
- src/StyleLexers/styleLexCPP.c
- src/StyleLexers/styleLexHTML.c
- src/StyleLexers/styleLexJS.c
- src/StyleLexers/styleLexJSON.c
- src/StyleLexers/styleLexLUA.c
- src/StyleLexers/styleLexMAK.c
- src/StyleLexers/styleLexPAS.c
- src/StyleLexers/styleLexPL.c
- src/StyleLexers/styleLexPS.c
- src/StyleLexers/styleLexPY.c
- src/StyleLexers/styleLexR.c
- src/StyleLexers/styleLexRUBY.c
- src/StyleLexers/styleLexStandard.c
- src/StyleLexers/styleLexTCL.c
- src/StyleLexers/styleLexXML.c
> + chg: Add extensions to StyleLexXXX.c (complete update)

- Build/Changes.txt
- language/np3_ja_jp/dialogs_ja_jp.rc
- language/np3_ja_jp/lexer_ja_jp.rc
- language/np3_ja_jp/menu_ja_jp.rc
> Translation >JP:picker, multi-sel ete. and Usage picker in Changes.txt

- Build/Changes.txt
> Update branch DevNewFeatures with Changes.txt

- language/common_res.h
- language/np3_de_de/strings_de_de.rc
- language/np3_en_gb/strings_en_gb.rc
- language/np3_en_us/strings_en_us.rc
- oniguruma/doc/API
- oniguruma/src/regcomp.c
- oniguruma/src/regenc.c
- oniguruma/src/regexec.c
- oniguruma/src/regint.h
- oniguruma/src/regparse.c
- oniguruma/src/regparse.h
- src/Notepad3.c
- src/Styles.c
@hpwamr : strings for en-US, en-GB and de-DE done, needed for all other languages 😉
> New (suppressible) Info-Dialog for "Preserve File Modification Timestamp" feature

- src/StyleLexers/styleLexAHKL.c
…which was a sorry victim of my confusion with the Control Flow block.
> AutoHotkey Lexer: re-add OnExit

- scintilla/src/AutoComplete.cxx
Source: https://sourceforge.net/p/scintilla/feature-requests/1031/
> Autocomplete selection: wrap movement

- src/Edit.c
- src/SciCall.h
> Convert Char to Hex and vice versa : work on (stream-)selection

- language/np3_hu_hu/dialogs_hu_hu.rc
Title says 2 new lines, but X-Times has already been translated, so only one change here.
> 2 new lines

- np3portableapp/build_np3portableapp.cmd
This reverts commit 9003c774517da3af738f08a1c83816d189ba66bd.
> Revert "+ ver: VS2019 version update - VS 16.3.7"

- language/np3_ja_jp/dialogs_ja_jp.rc
- language/np3_ja_jp/encode_ja_jp.rc
- language/np3_ja_jp/lexer_ja_jp.rc
- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ja_jp/strings_ja_jp.rc
- minipath/language/mp_ja_jp/dialogs_ja_jp.rc
- minipath/language/mp_ja_jp/menu_ja_jp.rc
> Translation >Japanese : 2019/Oct

- language/np3_ja_jp/strings_ja_jp.rc
> ja_jp: minor fix

- src/Helpers.c
- src/Version.h
- Windows 10 19H2 - 1909 Build 18363
> + Ver: VS2019 version update - VS 16.3.9

- src/Notepad3.c
> Disable HyperLink calltip on ESC, as long as caret is in hyperlink text range

- Build/minipath.ini
- language/np3_ja_jp/strings_ja_jp.rc
1. `String.rc`: I translate new parts, and adjust previous part. 
2. There was the same line in `minipath.ini`. Erase the first line in the original order.
> minipath.ini (delete same line),  ja_jp: STATUSBAR, Elevated,

- src/Config/Config.cpp
- src/Config/Config.h
- src/Dialogs.c
- src/Edit.c
- src/Notepad3.c
- test/test_files/encoding/Txtfiles/apache notes.txt
"Open 7-bit ASCII files in UTF-8 mode": encoding detection fallback UTF-8 or local ANSI CP
> Recent Files" History handling

- src/StyleLexers/styleLexStandard.c
- src/Styles.c
Related issue: https://github.com/rizonesoft/Notepad3/issues/1837.
> Fix IME color

- Build/Changes.txt
- language/np3_af_za/strings_af_za.rc
- language/np3_be_by/strings_be_by.rc
- language/np3_de_de/strings_de_de.rc
- language/np3_en_gb/strings_en_gb.rc
- language/np3_en_us/strings_en_us.rc
- language/np3_es_es/strings_es_es.rc
- language/np3_fr_fr/strings_fr_fr.rc
- language/np3_hu_hu/strings_hu_hu.rc
- language/np3_it_it/strings_it_it.rc
- language/np3_ja_jp/strings_ja_jp.rc
- language/np3_ko_kr/strings_ko_kr.rc
- language/np3_nl_nl/strings_nl_nl.rc
- language/np3_pl_pl/strings_pl_pl.rc
- language/np3_pt_br/strings_pt_br.rc
- language/np3_ru_ru/strings_ru_ru.rc
- language/np3_sk_sk/strings_sk_sk.rc
- language/np3_sv_se/strings_sv_se.rc
- language/np3_tr_tr/strings_tr_tr.rc
- language/np3_zh_cn/strings_zh_cn.rc
- test/test_files/encoding/UTF-8/í (issue #1924).json
- test/test_files/encoding/UTF-8/ú (issue #1924).json
- Translation of strings into FR, ES and NL
> MUI - Add "Reload Strings"

- language/np3_hu_hu/dialogs_hu_hu.rc
- language/np3_hu_hu/lexer_hu_hu.rc
- language/np3_hu_hu/menu_hu_hu.rc
- language/np3_hu_hu/strings_hu_hu.rc
The statusbar prefixes still to translate.
> New translations for v5.20 beta

- language/np3_zh_cn/menu_zh_cn.rc
> language/np3_zh_cn: Update translation for zh_CN

- language/np3_ja_jp/menu_ja_jp.rc
> Update menu_ja_jp.rc: jump selection

- language/np3_ja_jp/strings_ja_jp.rc
> strings_ja_jp.rc : largefile handle

- language/np3_zh_cn/menu_zh_cn.rc
> language/np3_zh_cn: Update keyboard shortcuts

- language/np3_ja_jp/menu_ja_jp.rc
> menu.ja_jp.rc: ligatures

- language/np3_zh_cn/menu_zh_cn.rc
- language/np3_zh_cn/strings_zh_cn.rc
> language/np3_zh_cn: Update translation

- language/np3_ja_jp/menu_ja_jp.rc
> Translation: menu_ja_jp.rc DPI

- language/np3_ja_jp/strings_ja_jp.rc
> Translation >Japanese : String: disclaimer

- language/np3_ja_jp/dialogs_ja_jp.rc
- language/np3_ja_jp/lexer_ja_jp.rc
- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ja_jp/strings_ja_jp.rc
- minipath/language/mp_ja_jp/dialogs_ja_jp.rc
- minipath/language/mp_ja_jp/strings_ja_jp.rc
> Translation >Japanese : adjust

- grepWinNP3/translationsNP3/日本語 （日本） [ja-JP].lang
> Translation >Japanese : 2020/May grepWin

- grepWinNP3/README.md
- grepWinNP3/src/SearchDlg.cpp
- grepWinNP3/src/last/version.h
- grepWinNP3/src/stdafx.h
- fix: portable backup in folders setting
> Upd: current grepWin development

- grepWinNP3/translationsNP3/Magyar (Magyarország) [hu-HU].lang
- with new strings
- with typo fixes
> grepWinNP3 Hungarian translation update

- grepWinNP3/translationsNP3/简体中文 （中国） [zh-CN].lang
> Update translation for zh_CN

- language/np3_pt_br/dialogs_pt_br.rc
Just to test commit and pull request
> Partial translation

- grepWinNP3/translationsNP3/日本語 （日本） [ja-JP].lang
- language/np3_ja_jp/lexer_ja_jp.rc
- language/np3_ja_jp/strings_ja_jp.rc
> Translation >Japanese : 2020/Jun, grepWinNP3, Lexer

- grepWinNP3/translationsNP3/日本語 （日本） [ja-JP].lang
Sorry. There was an untranslated section and a mistranslation by the previous translator.
> Translation >Japanese : 2020/Jun, grepWinNP3 2

- grepWinNP3/translationsNP3/日本語 （日本） [ja-JP].lang
- language/np3_ja_jp/strings_ja_jp.rc
Sorry for the pull requests again.
When I examined the previous translations(grepWinNP3), I found multiple mistranslations.
> Translation >Japanese : 2020/Jun, grepWinNP3 3

- src/Edit.c
- src/Styles.c
> Disable Main Window too, if non modal F/R or Schemes dialog is disabled

- grepWinNP3/translationsNP3/日本語 （日本） [ja-JP].lang
- language/np3_ja_jp/strings_ja_jp.rc
That part of "Capture" is untranslated because its function is unknown.
> Translation >Japanese : 2020/Jul, Readonly grepWinNP3 Capture

- grepWinNP3/translationsNP3/Magyar (Magyarország) [hu-HU].lang
- language/np3_hu_hu/strings_hu_hu.rc
From comment: https://github.com/rizonesoft/Notepad3/pull/2510#issuecomment-658035916
> More Hungarian translation added

- grepWinNP3/translationsNP3/Magyar (Magyarország) [hu-HU].lang
After looking through the interface on the latest RC, now I can provide better translations. Also tried to shorten strings as they were (some still are) lengthy.
> Shortening and adapting Hungarian some gernWinNP3 strings

- language/np3_ja_jp/menu_ja_jp.rc
> Translation >Japanese : 2020/Jul TinyExpr

- language/common_res.rc
- src/Config/Config.cpp
- src/Dialogs.c
- src/Dialogs.h
- src/Notepad3.c
- src/Styles.c
+ add: DPI-Aware treeview/listview lexer type icons
+ chg: DPI-Aware initial toolbar selection
> More DPI-Aware About/Schemes dialog

- grepWinNP3/translationsNP3/Português Brasileiro (Brasil) [pt-BR].lang
translation done with some uptades
> Update Português Brasileiro (Brasil) [pt-BR].lang

- src/Edit.c
- src/Edit.h
- src/Notepad3.c
+ fix: extend selection to next find (Ctrl+Alt+F2)
should fix regression #1126.
> Ensure selection visible (scroll to current position)

- language/common_res.h
- language/np3_de_de/lexer_de_de.rc
- language/np3_de_de/menu_de_de.rc
- language/np3_en_us/lexer_en_us.rc
- language/np3_en_us/menu_en_us.rc
- src/Config/Config.cpp
- src/Edit.c
- src/Helpers.c
- src/Helpers.h
- src/Notepad3.c
- src/Notepad3.h
- src/SciCall.h
- src/StyleLexers/EditLexer.h
- src/StyleLexers/styleLexStandard.c
- src/Styles.c
- src/TypeDefs.h
> Unicode Points Calltip on hover (#2598)

- src/Edit.c
- src/Helpers.c
- src/Notepad3.c
- src/SciCall.h
- src/TypeDefs.h
+ fix: Unicode Point detection
> Enhanced Color Tag contrast on hoover

- Build/Notepad3.ini
- grepWinNP3/src/AboutDlg.cpp
- src/Dialogs.c
- src/Dialogs.h
- src/Edit.c
- src/Styles.c
+ fix: center system's MessageBox in parent window
+ add: configuration for "Search in Files" toolbar label
> Relative calculation of title font size for AboutBox and CS dialog

- grepWinNP3/translationsNP3/한국어 (대한민국) [ko-KR].lang
simple ko-KR translation for grepWinNP3's new string line.
> ko-KR translation for the new line at grepWinNP3

- language/np3_ja_jp/lexer_ja_jp.rc
- language/np3_ja_jp/menu_ja_jp.rc
> Translation >Japanese : 2020/Aug, Unicode

- src/Dialogs.c
- src/Dialogs.h
- src/Helpers.c
- src/Helpers.h
- src/Notepad3.c
- src/Styles.c
+ fix: center dialog in parent (if parent is minimized)
> Add right-to-left title/frame layout for some dialog

- src/Dialogs.c
> Fix: reload language resource for about-box on init

- language/np3_fr_fr/dialogs_fr_fr.rc
- language/np3_fr_fr/lexer_fr_fr.rc
- language/np3_fr_fr/menu_fr_fr.rc
- language/np3_fr_fr/strings_fr_fr.rc
Corrected many French translations. Issue #2454
> MUI - Notepad3 translations update for fr-FR

- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ja_jp/strings_ja_jp.rc
> Translation >Japanese : 2020/Aug, FocusedView Bookmark et

- language/np3_ja_jp/strings_ja_jp.rc
@hpwamr Thanks your suggestion. I translated the rest part.
> Translation >Japanese : 2020/Aug, del history

- language/np3_ja_jp/menu_ja_jp.rc
> Translation >Japanese : 2020/Aug, ENCODING

- language/np3_ja_jp/dialogs_ja_jp.rc
- language/np3_ja_jp/lexer_ja_jp.rc
- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ja_jp/strings_ja_jp.rc
> Translation >Japanese : 2020/sep

- src/Notepad3.c
- tinyexpr/tinyexpr.c
... handle  `100 * 23% = ?`  and  `100 % 23 = ?`  correctly.
> TinyExpr: '%' operator: distinguish between modulo and percent operation by context

- language/np3_ja_jp/menu_ja_jp.rc
> Translation >Japanese : 2020/Sep, Dark

- grepWinNP3/src/SearchDlg.cpp
- grepWinNP3/src/SearchDlg.h
- grepWinNP3/src/last/version.h
@hpwamr : corresponding resource strings are only changed in en-US and de-DE grepWinNP3 language files
> grepWinNP3: save current "Stay On Top" settings on exit

- src/tinyexpr/tinyexpr.c
- keep in mind, that '%%' as percent op. is still deprecated.
> Fix minor issues regarding '%' operator interpretation

- src/Dialogs.c
- src/Edit.c
(0.selection)[F/R-DLG] - 1.previous-search/MRU-List - 2.clipboard
> Unify search-pattern retrieval

- grepWinNP3/translationsNP3/日本語 （日本） [ja-JP].lang
- language/np3_ja_jp/lexer_ja_jp.rc
- language/np3_ja_jp/menu_ja_jp.rc
Note: New string "About grepWinNP3" is not in the language file.
> Translation >Japanese : 2020/Sep, grepWin2.1.4.30

- grepWinNP3/sktoolslib_mod/Language.cpp
- grepWinNP3/src/SearchDlg.cpp
- grepWinNP3/src/Settings.cpp
+ fix: clone full .ini-file path for forked new instance
> grepWinNP3: wide char path names for language files

- Build/notepad3_setup.iss
- Build/notepad3_x86_setup.iss
- Minor adaption for beta Setup version
> +chg: Inno Setup - running minimum version Windows 7 SP1

- src/Notepad3.c
Fix #2972 (open) while keep dialog directory (workflow #2929).
> Fix Initial path on OpenFile dialog (load file)

- src/Edit.c
> Avoid wrap-around requester if there is no other possible occurrence

- src/Dialogs.c
- src/Dialogs.h
- src/Edit.c
+ fix: F/R dialog: Transform Backslash option glitch
+ fix: F/R dialog: message box in case of not matching pattern
> F/R Dialog: fixing minor issues

- src/Config/Config.cpp
- src/Notepad3.c
- src/Styles.c
- src/Styles.h
- src/TypeDefs.h
(->11pt  == former FullHD setting)
try to fix issue #3012
> Iinitial start screen resolution independent fixed base font size

- language/np3_ja_jp/lexer_ja_jp.rc
> Translation >Japanese : 2021/Jan, Kotlin

- scintilla/include/Platform.h
- scintilla/oniguruma/README.md
- scintilla/oniguruma/doc/API
- scintilla/oniguruma/src/oniguruma.h
- scintilla/oniguruma/src/regerror.c
- scintilla/oniguruma/src/regparse.c
- scintilla/oniguruma/src/regposix.c
- scintilla/oniguruma/src/regsyntax.c
- scintilla/win32/PlatWin.cxx
- scintilla/win32/ScintillaWin.cxx
ref. issue #3045
(using [Zufuliu's](https://github.com/zufuliu) changes for Scintilla)
> Enable horizontal scrolling by "Shift + Mouse-Wheel" 

- src/Dialogs.c
- src/Dialogs.h
- src/Notepad3.c
> InfoBox message icon DPI scaling

- lexilla/src/lexers_x/LexAHKL.cxx
> AHKL lexer: visual brace matching mix-ups

- language/common_res.h
- language/np3_de_de/strings_de_de.rc
- language/np3_en_us/strings_en_us.rc
- src/Config/Config.cpp
- src/Edit.c
- src/Notepad3.c
- src/TypeDefs.h
+ add: can be menu switched to preferred UI language
+ chg: insert date before time & tab separated
ref. issue #3073
> Use user locale for date/time insert format

- grepWinNP3/translationsNP3/Magyar (Magyarország) [hu-HU].lang
- language/np3_hu_hu/strings_hu_hu.rc
> Hungarian translation update

- language/np3_ja_jp/strings_ja_jp.rc
> Translation >Japanese : 2021/Feb wraparound

- scintilla/oniguruma/scintilla/OnigurumaRegExEngine.cxx
- src/Edit.c
- src/Edit.h
- src/SciCall.h
> F/R: fixes some issues around RegEx zero-length match/findings

- src/Dialogs.c
- src/Edit.c
- src/Notepad3.c
... if in Replace-Dlg (move selection to next match in Find-Dlg only)
> Do not move selection on search pattern change

- minipath/src/Helpers.h
- minipath/src/minipath.c
> MiniPath: Enable Mouse XButton usage ("browse back and forth")

- minipath/src/Config.cpp
- minipath/src/Dialogs.c
- minipath/src/Dialogs.h
- minipath/src/Dlapi.c
- minipath/src/Dlapi.h
- minipath/src/DropSource.cpp
- minipath/src/Helpers.c
- minipath/src/Helpers.h
- minipath/src/minipath.c
- minipath/src/minipath.h
+ fmt: AStyle formatting MiniPath sources
ref. issue #2274
> MiniPath: switch xbutton logic for browsing direction

- src/Notepad3.c
> Wrap-Around tooltip: use correct encoding

- src/Helpers.h
- src/Notepad3.c
> Fix URL-Decoding of file Hyperlinks ("file://...")

- scintilla/oniguruma/README.md
- scintilla/oniguruma/doc/API
- scintilla/oniguruma/src/oniguruma.h
- scintilla/oniguruma/src/regexec.c
- src/Edit.c
> Hyperlink RegEx pattern fixed to use valid Unicode

- language/np3_ja_jp/menu_ja_jp.rc
> Translation >Japanese : 2021/Mar URL path

- language/common_res.h
- language/np3_de_de/menu_de_de.rc
- language/np3_en_us/menu_en_us.rc
- src/Notepad3.c
+ add: Menu item for excusive File Locking (write, shared read)
ref. issue #3196
> File Lock: exclusive write/change, shared read

- src/Config/Config.cpp
- src/Notepad3.c
- src/TypeDefs.h
> Don't keep window top-most after returning from full-screen mode (F11 toggle)

- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ja_jp/strings_ja_jp.rc
Update "Doc Tail Chasing" -> "Monitoring Log".
> Translation >Japanese : 2021/Mar Update Doc Tail Chasing

- minipath/src/minipath.c
- minipath/src/minipath.rc
- minipath/src/resource.h
- src/Notepad3.rc
- src/resource.h
+ chk: review of Mono-Language compiler switch for Notepad3
> Mono-Language compiler switch for MiniPath

- src/Notepad3.c
- src/Notepad3.h
- src/Styles.c
maybe side-effect on issue #3247 too 🤔
> Cleanup code: SplitUndoTransaction on timeout resp. line-break (small bug-fix too)

- src/Config/Config.cpp
- src/Edit.c
- src/Notepad3.c
> PostMsg instead of SendMsg for immediate cmd on delayed message enqueuing

- src/Edit.c
- src/Notepad3.c
- src/uthash/utarray.h
- src/uthash/uthash.h
- src/uthash/utlist.h
- src/uthash/utringbuffer.h
- src/uthash/utstack.h
- src/uthash/utstring.h
+ chg: doing PostMsg instead of SendMsg for scheduled execution too
+ chg: sort delayed execution queue on enqueuing
> Update component : "uthash"  v.2.3.0

- scintilla/Scintilla.vcxproj.filters
- scintilla/oniguruma/.gitignore
- scintilla/oniguruma/HISTORY
- scintilla/oniguruma/README.md
- scintilla/oniguruma/doc/CALLOUTS.API
- scintilla/oniguruma/src/Makefile.windows
- scintilla/oniguruma/src/oniguruma.h
- scintilla/oniguruma/src/regcomp.c
- scintilla/oniguruma/src/regexec.c
- scintilla/oniguruma/src/regint.h
- scintilla/oniguruma/src/regparse.c
- scintilla/oniguruma/src/regparse.h
- scintilla/win32/ScintillaWin.cxx
> Horizontal mouse-wheel support and update to Oniguruma v6.9.7 (RC1)

- src/Dialogs.c
- src/Edit.c
- src/Notepad3.c
- src/resource.h
+ fix: center dialog in parent
ref. issues  #3264, #3265
> Fix mark all occurrences in case of reopened  F/R dialog

- src/Styles.c
… instead of background marker
> Mark occurrences: no additional bookmarker -> use invisible marker

- src/Notepad3.c
> Use 'Ctrl+' key to force dropping files into drop-target instance (reuse window)

- lexilla/lexers_x/LexJSON.cxx
- lexilla/lexlib/CharacterSet.h
- src/Edit.c
- src/Edit.h
- src/Notepad3.c
- src/SciCall.h
- src/Styles.c
> Fix lazy styling (no need for SCN_STYLENEEDED)

- language/np3_de_de/menu_de_de.rc
- language/np3_en_us/menu_en_us.rc
- src/Config/Config.cpp
- src/Dialogs.c
- src/Dialogs.h
- src/Edit.c
- src/Edit.h
- src/Notepad3.c
- src/SciCall.h
- src/TypeDefs.h
+ chg: drag-n-drop: allow multiple files to drop
+ chg: drag-n-drop: replace current file (Ctrl+  for new instance)
+ chg: menu/shortcut:  launch "New Empty Wnd" <-> "Duplicate Instance"
+ fix: prevent dup instance, if setting does not allow
ref. issue #3301
> Drag-n-Drop: allow multiple files to drop / change instance handling (new Wnd)

- Build/Notepad3.ini
- src/Config/Config.cpp
- src/Dialogs.c
- src/Notepad3.c
- src/TypeDefs.h
+ fix: Sticky Window Flag on launching new instance
> Configurable position offset on launching new instance (preserve old behavior)

- src/Dialogs.c
- src/Dialogs.h
- src/Notepad3.c
- src/TypeDefs.h
needs setting:
```
[Settings2]
LaunchInstanceWndPosOffset=24
LaunchInstanceFullVisible=true
```
> Standard windows behavior for cascading new instances (if configured)

- lexilla/doc/Lexilla.html
- lexilla/doc/LexillaHistory.html
- lexilla/lexers/LexCPP.cxx
- lexilla/scripts/LexillaGen.py
- lexilla/scripts/RunTest.bat
- lexilla/scripts/RunTest.sh
- lexilla/src/Lexilla/Lexilla.xcodeproj/project.pbxproj
- src/Dialogs.c
- src/Edit.c
- src/MuiLanguage.c
- src/MuiLanguage.h
- src/Notepad3.c
- src/TypeDefs.h
Cpp-Lexer fix merged from Lexilla (https://github.com/ScintillaOrg/lexilla/commit/5b92f7219a9fe9fb0ae4c5cc19f57c39185e4074)
> Update Lexilla component

- src/Edit.c
- src/Notepad3.c
- src/Notepad3.h
> Small correction to Line Cut feature (thin selection)

- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ja_jp/strings_ja_jp.rc
> Translation >Japanese : 2021/Apr instance status

- language/np3_af_za/strings_af_za.rc
- language/np3_be_by/strings_be_by.rc
- language/np3_de_de/strings_de_de.rc
- language/np3_el_gr/strings_el_gr.rc
- language/np3_en_gb/strings_en_gb.rc
- language/np3_en_us/strings_en_us.rc
- language/np3_es_419/strings_es_419.rc
- language/np3_es_es/strings_es_es.rc
- language/np3_fr_fr/strings_fr_fr.rc
- language/np3_hi_in/strings_hi_in.rc
- language/np3_hu_hu/strings_hu_hu.rc
- language/np3_id_id/strings_id_id.rc
- language/np3_it_it/strings_it_it.rc
- language/np3_ja_jp/strings_ja_jp.rc
- language/np3_ko_kr/strings_ko_kr.rc
- language/np3_nl_nl/strings_nl_nl.rc
- language/np3_pl_pl/strings_pl_pl.rc
- language/np3_pt_br/strings_pt_br.rc
- language/np3_pt_pt/strings_pt_pt.rc
- language/np3_ru_ru/strings_ru_ru.rc
- language/np3_sk_sk/strings_sk_sk.rc
- language/np3_sv_se/strings_sv_se.rc
- language/np3_tr_tr/strings_tr_tr.rc
- language/np3_vi_vn/strings_vi_vn.rc
- language/np3_zh_cn/strings_zh_cn.rc
- language/np3_zh_tw/strings_zh_tw.rc
- src/Notepad3.c
> Rremove short-note from wrap around match tooltip

- src/Styles.c
(based only on size and weight) as recommended to remove dependency on UI language
ref. issue #3344
> Removing the font-style string for font selection

- language/np3_ja_jp/menu_ja_jp.rc
> Translation >Japanese : 2020/Sep, line comment

- scintilla/include/Scintilla.h
- scintilla/src/CallTip.cxx
- scintilla/src/Editor.cxx
- scintilla/src/Platform.h
- scintilla/src/Style.cxx
- scintilla/src/Style.h
- scintilla/src/ViewStyle.cxx
- scintilla/win32/PlatWin.cxx
- src/Edit.c
- src/Edit.h
- src/Notepad3.c
- src/Styles.c
- src/TypeDefs.h
+ more intermediate font weight constants added
ref. issue #2221 
ref. issue #3344
> Copy multi-selection to clipboard:  separate each match by line-break

- language/Line numbers to translate.html
@hpwamr : better than the .png files: simple HTML, easy to learn (compare with visual result in Browser)
> HTML file to document string changes for Translators

- src/Styles.c
> Fix regression on schema color definition

- language/np3_ja_jp/dialogs_ja_jp.rc
- language/np3_ja_jp/menu_ja_jp.rc
> Translation >Japanese : 2021/Apr font

- minipath/res/MiniPath.exe.manifest
- minipath/src/Dialogs.c
- minipath/src/minipath.c
- scintilla/src/Editor.cxx
- scintilla/src/ViewStyle.cxx
- scintilla/src/ViewStyle.h
- scintilla/win32/PlatWin.cxx
> Some code cleanup (Scintilla Lib)

- language/np3_ja_jp/strings_ja_jp.rc
> Translation >Japanese : 2021/Apr DIR_EXISTS

- language/np3_ja_jp/dialogs_ja_jp.rc
> Translation >Japanese : 2021/Apr Color

- language/np3_ja_jp/menu_ja_jp.rc
> Translation >Japanese : 2021/May ignore vars

- src/Notepad3.c
- src/tinyexpr/tinyexpr.h
> TinyExpr: expr need not start with blank

- language/np3_it_it/dialogs_it_it.rc
Updated as per Line numbers to translate_2021-04.png
> Updated as per Line numbers to translate_2021-04.png

- lexilla/lexers_x/LexMarkdown.cxx
- src/Dialogs.c
- src/Dialogs.h
- src/Edit.c
- src/Notepad3.c
+fix: minor fixes Markdown-Lexer
ref. issue(s) #3405 and #3457
> Fix handling of F/R dialog pattern combo-box dropdown list

- grepWinNP3/translationsNP3/日本語 (日本) [ja-JP].lang
> Translation >Japanese : 2021/Jul Np3 2.0.8

- language/np3_ja_jp/lexer_ja_jp.rc
> Translation >Japanese : 2021/Jul KiXtart

- src/Edit.c
- src/Helpers.c
- src/Notepad3.c
- src/Notepad3.h
- src/TypeDefs.h
> Stop multiple file deleted notification

- language/np3_ja_jp/strings_ja_jp.rc
> Translation >Japanese : 2021/Jul reset standard

- src/Dialogs.c
- src/Dialogs.h
- src/Notepad3.c
> File on disk changed externally notification "@" in title bar

- src/Helpers.c
- src/Helpers.h
- src/Notepad3.c
- src/Styles.c
> Allow definition of line number for file:/// URL (separator is ':' )

- src/Dialogs.c
- src/Notepad3.c
- src/Notepad3.h
> Launching file URL (Alt+Click) with respect to flags "Reuse Window" and "Only one Instance per File"

- src/Notepad3.c
> Workaround for additional selection typing

- res/StdDarkModeScheme.ini
- src/StyleLexers/styleLexPROPS.c
> Add Configuration (Properties) Lexer: add style setting for Key

- grepWinNP3/translationsNP3/简体中文 (中国) [zh-CN].lang
- language/np3_zh_cn/dialogs_zh_cn.rc
- language/np3_zh_cn/lexer_zh_cn.rc
- language/np3_zh_cn/menu_zh_cn.rc
- language/np3_zh_cn/strings_zh_cn.rc
Signed-off-by: LIU Hao <lh_mouse@126.com>
> Update translation for zh_CN.

- grepWinNP3/translationsNP3/日本語 (日本) [ja-JP].lang
- language/np3_ja_jp/dialogs_ja_jp.rc
- language/np3_ja_jp/menu_ja_jp.rc
Thanks for everything. I saw the email and updated it.
GrepWin's Japanese had been updated in the original. It reflects.
> Translation >Japanese : 2021/Aug RC

- grepWinNP3/sktoolslib_mod/SimpleIni.h
- src/Config/SimpleIni.h
> Fix INVALID_HANDLE_VALUE in case of Win32 (32-bit) build (SimpleIni.h)

- grepWinNP3/sktoolslib_mod/SimpleIni.h
- src/Config/SimpleIni.h
> Previous fix reverted - missing .ini must not have an assertion failure, allowed case here

- src/Config/Config.cpp
- src/Dialogs.c
- src/Dialogs.h
- src/Notepad3.c
- src/TypeDefs.h
> Update status bar font size on system font size change

- scintilla/src/Editor.cxx
- scintilla/win32/ScintillaWin.cxx
- src/Notepad3.c
- src/Print.cpp
ref. issue #3606
ref. issue #3605
> Caret change to hand over hyperlink only if ctrl is pressed

- src/Notepad3.c
- src/TypeDefs.h
> Web-Action commands should use also user-defined app to open hyperlinks

- src/Dialogs.c
- src/Notepad3.c
> Fix initial factory window position

- Build/Themes/Dark.ini
- Build/Themes/Obsidian.ini
- src/Notepad3.vcxproj
- src/Notepad3.vcxproj.filters
> Better hyperlink style in dark themes "Dark" and "Obsidian"

- src/Edit.c
- src/Notepad3.c
- src/SciCall.h
- src/TypeDefs.h
> Dark Mode aware auto-completion-list-box

- src/Notepad3.c
- src/Notepad3.h
> Add context menu for menu bar

- src/Notepad3.c
> Enable context menu for status bar

- src/Config/Config.cpp
- src/Dialogs.c
- src/Dialogs.h
- src/Notepad3.c
- src/Notepad3.h
- src/TypeDefs.h
- src/win/dlgs.h
> Dark-Mode menu bar coloring (except bottom line)

- Readme.txt
- grepWinNP3/translationsNP3/Nederlands (Nederland) [nl-NL].lang
- language/common_res.rc
- language/np3_nl_nl/dialogs_nl_nl.rc
- language/np3_nl_nl/strings_nl_nl.rc
- minipath/language/mp_nl_nl/strings_nl_nl.rc
+ Add: Update "Acknowledgements" list
> +Chg: Small corrections in dialog F/R in "nl-NL"

- grepWinNP3/src/SearchDlg.cpp
- grepWinNP3/src/SearchDlg.h
- src/Edit.c
+fix: grepWinNP3  switching radio file size search settings (ref. issue #3727)
> Fix wrong format for reporting number of replaced occurrences "In Selection"

- src/Edit.c
> Find/Repl dialog - empty search string should have no match (blue)

- src/Notepad3.c
- src/Styles.c
> Switch to Scintilla default idle styling mode (none)

- src/Dialogs.c
- src/Notepad3.c
> Fix positioning multi instance launch

- src/Config/Config.cpp
- src/Notepad3.c
- src/Notepad3.h
> Fix positioning on separate instance launch

- Build/Notepad3.ini
- src/Config/Config.cpp
- src/Dialogs.c
- src/Notepad3.c
- src/TypeDefs.h
> Fixing some more findings on positioning multi instance launch

- Build/Themes/Dark.ini
- Build/Themes/Obsidian.ini
- Build/Themes/Sombra.ini
- src/Config/Config.cpp
- src/Dialogs.c
- src/Dialogs.h
- src/Notepad3.c
- src/PathLib.c
- src/PathLib.h
- src/Styles.c
- src/Styles.h
- src/TypeDefs.h
- ref. issue #3837
- ref. issue #3838
> Fix reading initial style config

- src/Config/Config.cpp
- src/Config/Config.h
- src/Dialogs.c
- src/MuiLanguage.c
- src/Notepad3.c
- src/PathLib.c
- src/PathLib.h
- src/Styles.c
- src/Styles.h
> Some LongPath-Lib refactorings

- src/Styles.c
> Fix locale settings dependent Themes Menu (Standard Config)

- src/PathLib.c
> Fix parsing file arg: relative from working dir

- res/StdDarkModeScheme.ini
- src/StyleLexers/styleLexFortran.c
> Fortran Lexer keyword/function enhancement

- src/Notepad3.c
- src/Notepad3.h
- src/PathLib.c
> Fix performance issue on pasting clipboard

- language/common_res.rc
- src/Dialogs.c
(does not help for URLs ending in dash)
> AboutBox's RichEdit Ctrl: enable more options for EM_AUTOURLDETECT

- src/Config/Config.cpp
- src/Config/Config.h
- src/Edit.c
- src/Notepad3.c
- src/Styles.c
+chg: URL detector: double-quote should not be valid URL character
ref. issue #3886
ref. issue #3875
> Fix F/R pattern history: clear all not persisted to .ini file

- language/np3_de_de/menu_de_de.rc
- language/np3_en_us/menu_en_us.rc
- src/Notepad3.rc
(and back) conversion.
ref. issue #3571
> Ctrl/Alt+F10 as Accelerator-Keys for Filesystem-Path to URL

- src/StyleLexers/EditLexer.c
> Fix XML/HTML Stream Comment

- language/np3_tr_tr/menu_tr_tr.rc
> New line update

- grepWinNP3/grepWinNP3.vcxproj
- language/np3_de_de/menu_de_de.rc
- src/Edit.c
- src/Edit.h
- src/Helpers.c
- src/Helpers.h
- src/Notepad3.c
> Allow switching encoding for empty document

- src/Config/Config.cpp
- src/Dialogs.c
- src/Dialogs.h
- src/Edit.c
- src/Notepad3.c
- src/crypto/crypto.c
> Fix ID mismatch using 'enter' to close infobox (vs. 'yes/ok' button)

- scintilla/win32/ScintillaWin.cxx
> drag&drop text snippet while ALT-Key down will not scroll

- src/Edit.c
> mark all occurrences: move caret to end of main selection

- src/Edit.c
- src/Notepad3.c
further regressions:
-  Shift+F3 (find prev.) broken
- ???
> Fix: regression caused by previous fix

- language/common_res.h
- language/np3_de_de/strings_de_de.rc
- language/np3_en_us/strings_en_us.rc
- src/Edit.c
- src/Notepad3.c
+fix: occurrence counter for "current word" mode
> Msg box on editing read-only document

- src/crypto/crypto.c
> Security enhancement of AES Encryption feature

- src/crypto/crypto.c
> Fix DarkMode issue in Decrypt dialog

- src/TypeDefs.h
> Change default settings for Auto-Save beta version

- src/Config/Config.cpp
- src/Config/Config.h
- src/Dialogs.c
- src/Notepad3.c
- src/StyleLexers/styleLexStandard.c
- src/Styles.c
- src/Version.h
+chg: using 'Cascadia Mono' as default for pure 'Text File' scheme (if available)
> Fix: writing wrong scheme to .ini-file

- src/Styles.c
> Fix dark mode color style scheme global from common base/2nd

- src/Notepad3.c
> Fix directory locking of current file.

- scintilla/src/Platform.h
- scintilla/win32/PlatWin.cxx
- src/Notepad3.c
- src/Styles.c
- Scintilla-Patch shamelessly taken from Zufuliu's Notepad2-mod (great job)
ref. issue #4150
> Fix Font selection (if font face-name does not match family-name)

- src/Styles.c
> Fix propagate default font to undefined-font styles

- src/Version.h
+upd: version info for MS VS2022 (v17.3.4) update
> +upd: version info for MS VS2022 (v17.3.4) update

- src/Notepad3.c
- src/Notepad3.h
- src/resource.h
> Titlebar update on change

- src/Helpers.c
- src/Notepad3.c
- src/Version.h
> Fix Win10/11 build number to name mapping

- src/Edit.c
> "Modify Lines" feature (using tinyexpr) - add error message

- lexilla/Lexilla.vcxproj.filters
- lexilla/lexers_x/CharSetX.h
- lexilla/lexers_x/LexCSV.cxx
- lexilla/lexers_x/LexJSON.cxx
- lexilla/lexers_x/LexKotlin.cxx
- lexilla/lexers_x/LexMarkdown.cxx
- lexilla/lexers_x/LexTOML.cxx
- lexilla/lexers_x/orig/LexJSON.cxx
- lexilla/lexers_x/orig/LexMarkdown.cxx
- src/Notepad3.c
- src/SciCall.h
> Avoid horizontal line scrolling on File Revert (F5)

- Build/Themes/Dark.ini
- Build/Themes/Obsidian.ini
- Build/Themes/Sombra.ini
- res/StdDarkModeScheme.ini
- src/Config/Config.cpp
- src/Config/Config.h
- src/Notepad3.c
- src/Styles.c
> Fix Theme handling

- src/Notepad3.c
- src/Notepad3.h
> Fix broken reload file (broken by check for single file instance)

- src/Edit.c
> Fix error message on loading empty file

- src/StyleLexers/styleLexAVS.c
> minor enhancements for AviSynth Lexer

- Readme.txt
- grepWinNP3/translationsNP3/正體中文 (中國台灣) [zh-TW].lang
- grepWinNP3/translationsNP3/简体中文 (中国大陆) [zh-CN].lang
- language/common_res.rc
- language/np3_zh_tw/strings_zh_tw.rc
- minipath/language/mp_zh_tw/strings_zh_tw.rc
- src/VersionEx.h
chg: Translator name to "lhmouse" for  "zh-TW"
> MUI - Rectify names for "zh-CN" and "zh-TW"

- language/np3_af_za/dialogs_af_za.rc
- language/np3_be_by/dialogs_be_by.rc
- language/np3_de_de/dialogs_de_de.rc
- language/np3_el_gr/dialogs_el_gr.rc
- language/np3_en_gb/dialogs_en_gb.rc
- language/np3_en_us/dialogs_en_us.rc
- language/np3_es_es/dialogs_es_es.rc
- language/np3_es_mx/dialogs_es_mx.rc
- language/np3_fr_fr/dialogs_fr_fr.rc
- language/np3_hi_in/dialogs_hi_in.rc
- language/np3_hu_hu/dialogs_hu_hu.rc
- language/np3_id_id/dialogs_id_id.rc
- language/np3_it_it/dialogs_it_it.rc
- language/np3_ja_jp/dialogs_ja_jp.rc
- language/np3_ko_kr/dialogs_ko_kr.rc
- language/np3_nl_nl/dialogs_nl_nl.rc
- language/np3_pl_pl/dialogs_pl_pl.rc
- language/np3_pt_br/dialogs_pt_br.rc
- language/np3_pt_pt/dialogs_pt_pt.rc
- language/np3_ru_ru/dialogs_ru_ru.rc
- language/np3_sk_sk/dialogs_sk_sk.rc
- language/np3_sv_se/dialogs_sv_se.rc
- language/np3_tr_tr/dialogs_tr_tr.rc
- language/np3_vi_vn/dialogs_vi_vn.rc
- language/np3_zh_cn/dialogs_zh_cn.rc
- language/np3_zh_tw/dialogs_zh_tw.rc
- minipath/language/mp_fr_fr/dialogs_fr_fr.rc
+ Minors corrections in layout
> MUI - Adjust Notepad3 in fr-FR to correctly fit at display scale of 125% (stage_3)

- grepWinNP3/translationsNP3/Italiano (Italia) [it-IT].lang
- language/np3_it_it/dialogs_it_it.rc
- language/np3_it_it/menu_it_it.rc
- language/np3_it_it/strings_it_it.rc
Inserted semantic improvements and translated forgotten strings.
> Other small updates

- src/Styles.c
- src/Styles.h
> set alpha (80) for "highlight current line" translucency, if not given

- language/np3_en_gb/menu_en_gb.rc
- language/np3_en_us/menu_en_us.rc
- language/np3_hi_in/menu_hi_in.rc
- language/np3_id_id/menu_id_id.rc
- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ko_kr/menu_ko_kr.rc
- language/np3_vi_vn/menu_vi_vn.rc
- language/np3_zh_cn/menu_zh_cn.rc
- language/np3_zh_tw/menu_zh_tw.rc
Issue in PR: https://github.com/rizonesoft/Notepad3/pull/4375#issuecomment-1352523845
> MUI - Minor corrections of "Menu Shortcuts - Settings"

- src/Config/Config.cpp
- src/PathLib.c
> Use alternate path, if Path_GetKnownFolder() failed

- res/StdDarkModeScheme.ini
- src/Styles.c
(cherry picked from commit 3e27626cf1063df262118724eeb9ab2986d613b8)
> Allow Line Number color to be alpha blended (e.g. DarkMode)

- src/Notepad3.c
> Fix Load-Toolbar-Bitmap handling.

- src/Notepad3.c
- src/PathLib.c
> Fix path to module relative representation

- src/Notepad3.c
- src/PathLib.c
- src/PathLib.h
ref. issue #4054
@hpwamr : please test if other file/path argument variants are not broken now (e.g. UNC-Paths)
> Fix some WSL2 (Linux) path issues

- language/np3_ja_jp/lexer_ja_jp.rc
- language/np3_ja_jp/strings_ja_jp.rc
> Translation >Japanese : 2023 RC2

- src/Edit.c
(EscCtrlChr) in F/R-Box is used
ref. issue #3769
> +fix: trigger mark-all-occ after transform backslash 

- Build/Changes.txt
- src/Dialogs.c
- src/Dialogs.h
- src/Notepad3.c
- src/Notepad3.h
- src/Version.h
+fix: Animated minimize (taskbar or tray), restore w/o white splash
+upd: Changes.txt and VS2019 version display
ref. issue #4471
> Try to fix Initial white display (splash) in case of Dark Mode Win

- src/Edit.c
- src/Edit.h
- src/EncodingDetection.cpp
- src/Notepad3.c
- src/SciCall.h
- src/Styles.c
> Speedup loading files with very long lines

- src/Edit.c
ref. issue #4515
@hpwamr : this is a severe bug and needs to add a hotfix release of last released version
> +fix: infinite loop using SCI_REPLACETARGETMINIMAL in replace all loop in range

- Build/notepad3_x64_setup.iss
- Build/notepad3_x86_setup.iss
- Issue [#4518](https://github.com/rizonesoft/Notepad3/issues/4518#issuecomment-1416665195)
> MUI - Installer script resets "Theme files" only on user decision.

- src/SciCall.h
- src/StyleLexers/styleLexStandard.c
- src/Styles.c
> Fix line spacing in TEXT Lexer

- Notepad3.sln
- np3encrypt/np3encrypt.vcxproj
- np3encrypt/np3encrypt.vcxproj.filters
- src/Version.h
- src/crypto/crypto.c
- src/crypto/notepadcrypt.c
+fix: use random IV for np3encrypt
+ver: VS2019 compiler Version added
@hpwamr : maybe optional (default=OFF) installer feature for np3encrypt.exe
ref. issue #4546
> Add np3encrypt project to solution (cmd-ln tool)

- language/common_res.h
- language/np3_af_za/menu_af_za.rc
- language/np3_be_by/menu_be_by.rc
- language/np3_de_de/menu_de_de.rc
- language/np3_el_gr/menu_el_gr.rc
- language/np3_en_gb/menu_en_gb.rc
- language/np3_en_us/menu_en_us.rc
- language/np3_es_es/menu_es_es.rc
- language/np3_es_mx/menu_es_mx.rc
- language/np3_fr_fr/menu_fr_fr.rc
- language/np3_hi_in/menu_hi_in.rc
- language/np3_hu_hu/menu_hu_hu.rc
- language/np3_id_id/menu_id_id.rc
- language/np3_it_it/menu_it_it.rc
- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ko_kr/menu_ko_kr.rc
- language/np3_nl_nl/menu_nl_nl.rc
- language/np3_pl_pl/menu_pl_pl.rc
- language/np3_pt_br/menu_pt_br.rc
- language/np3_pt_pt/menu_pt_pt.rc
- language/np3_ru_ru/menu_ru_ru.rc
- language/np3_sk_sk/menu_sk_sk.rc
- language/np3_sv_se/menu_sv_se.rc
- language/np3_tr_tr/menu_tr_tr.rc
- language/np3_vi_vn/menu_vi_vn.rc
- language/np3_zh_cn/menu_zh_cn.rc
- language/np3_zh_tw/menu_zh_tw.rc
- src/Config/Config.cpp
- src/Notepad3.c
- src/TypeDefs.h
As with tags and parentheses, I added the ability to automatically close quotation marks, speeding up code writing with strings.
> New Quotation Mark Auto-Close Functionality

- res/StdDarkModeScheme.ini
- src/StyleLexers/styleLexStandard.c
- chg to:  "font:Consolas; size:-2; fore:#008080"
> MUI - Synchro all "Margins and Line Numbers"

- src/Edit.c
- src/Notepad3.c
- test/test_files/StyleLexers/styleLexCPP/Config.cpp
... (e.g. called by grepWinNP3)
ref. issue #3467
> Repair jump to line (Alt+Click) and related command line search… 

- src/Notepad3.c
- src/SciCall.h
> Enhancement for auto-close char-pairs

- src/Edit.c
- src/TypeDefs.h
> Include change-history-markers for bookmark find next/previous

- Build/Notepad3.ini
- res/StdDarkModeScheme.ini
- src/Config/Config.cpp
- src/Helpers.c
- src/Notepad3.c
- src/StyleLexers/styleLexStandard.c
- src/Styles.c
- src/TypeDefs.h
> Make Code/Text font prio list configurable

- src/Edit.c
> Navigate marker: consecutive change-marker handled as single mark

- grepWinNP3/src/RegexReplaceFormatter.h
- grepWinNP3/src/SearchDlg.cpp
- grepWinNP3/src/ShellContextMenu.cpp
- grepWinNP3/src/last/version.h
> Fix grepWinNP3: properly search from the file beginning again

- src/Notepad3.c
- src/SciCall.h
> Delete matching brace/quote, if content in between is empty

- src/Edit.c
> Fix goto marker next/prev

- src/Styles.c
> Fix: remove session state from default font from list retrieval

- grepWinNP3/translationsNP3/Bahasa Indonesia (Indonesia) [id-ID].lang
First version of translation for grepWinNP3, still need revision if needed.
> Add grepWinNP3 Indonesian translation

- grepWinNP3/translationsNP3/Bahasa Indonesia (Indonesia) [id-ID].lang
New revision translation :
- new sentence order
- new word choice
- remove unecessery text
- fix capitalization
> Update Indonesian translation for grepWinNP3

- minipath/language/mp_id_id/menu_id_id.rc
- minipath/language/mp_id_id/strings_id_id.rc
Currently translated Mnipath files :
- strings_id_id.rc
- menu_id_id.rc
dialogs_id_id.rc, not yet.
> Add new Minipath translation (id-ID)

- minipath/language/mp_id_id/menu_id_id.rc
- minipath/language/mp_id_id/strings_id_id.rc
Revision and Fix string, word and sentences.
> Update Minipath Indonesian translation (id-ID)

- src/Dialogs.c
- src/Notepad3.c
- src/PathLib.c
> Fix: creating new file in current working directory

- src/Notepad3.c
> Fix missing file path display name

- src/Config/Config.cpp
- src/Print.cpp
> Default Print Colour Mode depending on Dark/Light Mode

- scintilla/oniguruma/scintilla/OnigurumaRegExEngine.cxx
- scintilla/oniguruma/src/ascii.c
- scintilla/oniguruma/src/oniguruma.h
- scintilla/oniguruma/src/regenc.c
- scintilla/oniguruma/src/regenc.h
- scintilla/oniguruma/src/regexec.c
- scintilla/oniguruma/src/utf8.c
- src/Edit.c
- src/TypeDefs.h
> Fix Oniguruma line-break handling (CRLF & CR) support

- language/np3_id_id/menu_id_id.rc
- language/np3_id_id/strings_id_id.rc
Full Translation for menu rc
Add some translation in string rc
> Add Indonesian (id-ID) Translation for Notepad3

- grepWinNP3/translationsNP3/Nederlands (Nederland) [nl-NL].lang
> Update Nederlands (Nederland) [nl-NL].lang

- language/np3_it_it/strings_it_it.rc
> Aligned discordant definition

- language/np3_id_id/dialogs_id_id.rc
- language/np3_id_id/menu_id_id.rc
- language/np3_id_id/strings_id_id.rc
Add Translation :
- dialogs_id_id.rc
Update Translation :
- menu_id_id.rc
- strings_id_id.rc
> Add Last Indonesian Translation (id-ID) for Notepad3

- language/np3_id_id/dialogs_id_id.rc
- language/np3_id_id/menu_id_id.rc
- language/np3_id_id/strings_id_id.rc
- minipath/language/mp_id_id/dialogs_id_id.rc
Add Translation :
- minipath/dialogs_id_id.rc
Update Translation :
- notepad3/dialogs_id_id.rc
- notepad3/menu_id_id.rc
- notepad3/strings_id_id.rc
I have recheck and update translation to short some word / sentences in Notepad3, for Minipath not yet.
> Add Last Indonesian Translation for Minipath

- src/Config/Config.cpp
- src/Dialogs.c
- src/EncodingDetection.cpp
- src/Notepad3.c
- src/TypeDefs.h
- ref. issue #4730
- ref. issue #4710
> Regression: save read-only file

- language/np3_id_id/dialogs_id_id.rc
- language/np3_id_id/menu_id_id.rc
- language/np3_id_id/strings_id_id.rc
- add new translation (follow upstream)
- update translation <- dont worry, i use short word for translation
- indent some space
> Indonesian Translation (id-ID) for Notepad3

- src/Dialogs.c
- src/Edit.c
- src/Helpers.c
- src/Notepad3.c
- src/SciCall.h
> Minor enhancement on log file monitoring

- Build/Notepad3.ini
- lexilla/lexers/LexInno.cxx
- src/Config/Config.cpp
- src/Notepad3.c
- src/TypeDefs.h
> Option: do not save blank new files

- src/Notepad3.c
> Fix 'Single File Instance' flag handling

- src/Dialogs.c
- src/Dialogs.h
- src/Edit.c
- src/Notepad3.c
- src/SciCall.h
- src/StyleLexers/EditLexer.c
- src/TypeDefs.h
- src/uchardet/uchardet/Origin_GitHub.url
- test/test_files/StyleLexers/styleLexHTML/Design.html
ref. issue #4812
ref. issue #4814
> Fixing comment hotkey on PHP embedded code and removing square-brackets from valid codepoints of URL

- language/np3_pt_br/dialogs_pt_br.rc
- src/Edit.c
- src/Notepad3.c
- src/SciCall.h
- src/StyleLexers/EditLexer.c
ref. issue #4834 
ref. issue #4837
> zoom tooltip positioning and auto-completion list optimization

- src/Edit.c
- src/Styles.c
> Set color of horizontal ruler (folded block) to line number coloring

- src/Edit.c
- src/Helpers.c
- src/Helpers.h
- src/Notepad3.c
- src/SciCall.h
- src/Styles.c
-   using system's message font face (std: Segoe UI),
-   foregr high-contrast on margin background color
> Minor changes: CallTip/ToolTip (zoom)

- Build/Notepad3.ini
- language/common_res.h
- language/np3_de_de/strings_de_de.rc
- language/np3_en_us/strings_en_us.rc
- src/Config/Config.cpp
- src/Notepad3.c
> Add Reset Zoom toolbar button

- language/np3_id_id/strings_id_id.rc
Add Translation for string_id_id.rc
Based on "Line numbers to translate_2023-06"
> id-ID Translation

- src/Dialogs.c
- src/Dialogs.h
- src/Notepad3.c
- src/Styles.c
> Minor optimizations on initial window startup

- language/common_res.h
- language/np3_af_za/strings_af_za.rc
- language/np3_be_by/strings_be_by.rc
- language/np3_de_de/strings_de_de.rc
- language/np3_el_gr/strings_el_gr.rc
- language/np3_en_gb/strings_en_gb.rc
- language/np3_en_us/strings_en_us.rc
- language/np3_es_es/strings_es_es.rc
- language/np3_es_mx/strings_es_mx.rc
- language/np3_fr_fr/strings_fr_fr.rc
- language/np3_hi_in/strings_hi_in.rc
- language/np3_hu_hu/strings_hu_hu.rc
- language/np3_id_id/strings_id_id.rc
- language/np3_it_it/strings_it_it.rc
- language/np3_ja_jp/strings_ja_jp.rc
- language/np3_ko_kr/strings_ko_kr.rc
- language/np3_nl_nl/strings_nl_nl.rc
- language/np3_pl_pl/strings_pl_pl.rc
- language/np3_pt_br/strings_pt_br.rc
- language/np3_pt_pt/strings_pt_pt.rc
- language/np3_ru_ru/strings_ru_ru.rc
- language/np3_sk_sk/strings_sk_sk.rc
- language/np3_sv_se/strings_sv_se.rc
- language/np3_tr_tr/strings_tr_tr.rc
- language/np3_vi_vn/strings_vi_vn.rc
- language/np3_zh_cn/strings_zh_cn.rc
- language/np3_zh_tw/strings_zh_tw.rc
- src/Notepad3.c
> Add new Toolbar button "New Empty Window"

- src/Notepad3.c
> Fix: 'LaunchInstanceFullVisible' feature

- language/np3_de_de/strings_de_de.rc
- language/np3_en_gb/strings_en_gb.rc
- language/np3_en_us/strings_en_us.rc
- src/Notepad3.c
> Change: allow not suitable toolbar dimension

- src/Edit.c
> Fix: save also empty replace string in history

- scintilla/oniguruma/scintilla/OnigurumaRegExEngine.cxx
- scintilla/oniguruma/src/regenc.c
- scintilla/oniguruma/src/regenc.h
- src/Edit.c
- src/SciCall.h
- test/test_files/regex/test_eol_eof.txt
> Change: patch Oniguruma engine to accept EOF as line-terminator

- scintilla/oniguruma/README.md
- src/Notepad3.c
- src/SciCall.h
> Fix regression: do not generally move selection to top on view

- scintilla/oniguruma/scintilla/OnigurumaRegExEngine.cxx
- scintilla/oniguruma/src/regenc.c
- src/Edit.c
- src/SciCall.h
- test/test_files/regex/test_eol_eof.txt
> Fix regEx search with begin/end line meta chars

- src/Edit.c
- src/EncodingDetection.cpp
- src/Notepad3.c
- src/SciCall.h
- src/Styles.c
- src/TypeDefs.h
> Try to speed-up large file loading

- src/Notepad3.c
fixes issue #4931
rejects issue #4790
> Fix: Show hidden menu bar on Alt or F10 key

- Build/Changes.txt
- minipath/res/MiniPath.exe.manifest
- res/Notepad3.exe.manifest
> MUI - Commit before release build "Notepad3 6.23.731.1 rc"

- language/np3_id_id/strings_id_id.rc
Add translation based on "Line number to translate on July 2023".
> Translation id-ID / July 2023

- Build/Notepad3.ini
- np3encrypt/np3encrypt.vcxproj
- src/Config/Config.cpp
- src/Dialogs.c
- src/Dialogs.h
- src/Notepad3.c
- src/TypeDefs.h
> +add: opt. to disable animated max./min. window ([Settings2] DrawAnimatedWindow)]

- src/Edit.c
- src/StyleLexers/EditLexer.c
+add: Python stream comment hack
ref issue #4983
> Python Line Comment : respect indents

- Build/notepad3_x64_setup.iss
- Build/notepad3_x86_setup.iss
- Readme.txt
- language/common_res.rc
- src/Version.h
MUI - Some adjustments of INNO Setup Installers
> +upd: version info for MS VS2022 (v17.7.4) update

- language/np3_id_id/dialogs_id_id.rc
Translate for number lines 99 and 133.
> Add Indonesian Translate

- src/Styles.c
secondary and inactive
ref. issue #5021
> Using selection color also for not focused selections

- src/Edit.c
- src/Edit.h
- src/Notepad3.c
> Fix: VS Studio line-cut behavior on empty selection

- src/Dialogs.c
- src/Dialogs.h
- src/Edit.c
- src/Helpers.c
- src/Helpers.h
- src/Notepad3.c
ref. issue #5051
ref. issue #5053
> Reduce window flickering, fix cut last line

- scintilla/win32/ScintillaWin.cxx
- src/Notepad3.c
> Fix Ctrl+Up/Down should keep selection

- grepWinNP3/src/ShellContextMenu.cpp
> Fix grepWinNP3: Search results context menu: fix Open with Editor

- Build/Notepad3.ini
- src/Config/Config.cpp
- src/Dialogs.c
- src/Dialogs.h
- src/Notepad3.c
- src/TypeDefs.h
> +fix: Settings2:DrawAnimatedWindow - support system settings

- src/Config/SimpleIni.h
- other (invalid) suffixes will yield default value
> Config-File: allow space or comment char after integer and float values

- src/Notepad3.c
- src/SciCall.h
- src/Styles.c
> Reusing size: definition of "Indentation Guide" scheme settings for text area offset to margin area

- src/Notepad3.c
> Need PostMessage(WM_THEMECHANGED)  event  after recoding document

- src/Edit.c
- src/Notepad3.c
- src/SciCall.h
> try to preserve caret position after recoding

- src/Edit.c
- src/Notepad3.c
- src/Notepad3.h
- src/SciCall.h
> Preserve caret position after re-encoding

- src/Styles.c
> Limit width of left dead margin text area to max base font width (char width)

- Build/Notepad3.ini
- src/Config/Config.cpp
- src/Dialogs.c
- src/Dialogs.h
- src/Helpers.c
- src/Notepad3.c
- src/TypeDefs.h
avoids global system settings activation
> DrawAnimatedWindow: only toggle between system settings and suppress-animation if used in system settings

- scintilla/oniguruma/scintilla/OnigurumaRegExEngine.cxx
- scintilla/oniguruma/src/utf8.c
- src/Dialogs.c
- src/Edit.c
- src/Notepad3.c
- ref. issue #5056 
- ref. issue #5124
- ref. issue #5125
> Fix:  TAB selection on empty line,  toolbar missing if started minimized, change RegEx syntax for horizontal space matching

- src/Edit.c
- src/Notepad3.c
> Fix remove duplicate lines

- scintilla/win32/ScintillaWin.cxx
- src/Config/Config.cpp
- src/Edit.c
- src/Helpers.h
- src/Notepad3.c
- src/Version.h
> fix mouse cursor flickering in case of "hide mouse while typing"

- src/Notepad3.c
- src/Notepad3.h
> fix minor issues related to "autoload recent file" feature

- language/Line numbers to translate.txt
- src/Version.h
MUI - "Added or Modified" items in May 2024
> +upd: version info for MS VS2022 (v17.10.1) update

- language/np3_id_id/menu_id_id.rc
Change the word in line 292-293 also add Indonesian translation for line 494 (May 2024).
> Update Indonesian Translation

- src/Notepad3.c
> Fix: Update Toolbar in case of Undo/Redo

- src/Notepad3.c
> Fix: delete line (Ctrl+Shift+D) - fix last line handling

- language/np3_hu_hu/menu_hu_hu.rc
> Hungarian translation update fix

- language/np3_it_it/dialogs_it_it.rc
- language/np3_it_it/menu_it_it.rc
> New strings translated

- language/np3_af_za/menu_af_za.rc
- language/np3_be_by/menu_be_by.rc
- language/np3_de_de/menu_de_de.rc
- language/np3_el_gr/menu_el_gr.rc
- language/np3_en_gb/menu_en_gb.rc
- language/np3_en_us/menu_en_us.rc
- language/np3_es_es/menu_es_es.rc
- language/np3_fi_fi/menu_fi_fi.rc
- language/np3_fr_fr/menu_fr_fr.rc
- language/np3_hi_in/menu_hi_in.rc
- language/np3_hu_hu/menu_hu_hu.rc
- language/np3_id_id/menu_id_id.rc
- language/np3_it_it/menu_it_it.rc
- language/np3_ja_jp/menu_ja_jp.rc
- language/np3_ko_kr/menu_ko_kr.rc
- language/np3_nl_nl/menu_nl_nl.rc
- language/np3_pl_pl/menu_pl_pl.rc
- language/np3_pt_br/menu_pt_br.rc
- language/np3_pt_pt/menu_pt_pt.rc
- language/np3_ru_ru/menu_ru_ru.rc
- language/np3_sk_sk/menu_sk_sk.rc
- language/np3_sv_se/menu_sv_se.rc
- language/np3_tr_tr/menu_tr_tr.rc
- language/np3_vi_vn/menu_vi_vn.rc
- language/np3_zh_cn/menu_zh_cn.rc
- language/np3_zh_tw/menu_zh_tw.rc
ref. issue https://github.com/rizonesoft/Notepad3/issues/5348
> MUI - Moving the "Search" menu to the Toolbar

- Build/Changes.txt
- Build/Docs/KeyboardShortcuts.txt
- Build/Docs/Notepad3.txt
- License.txt
- Readme.md
- Readme.txt
- language/Line numbers to translate.txt
- language/common_res.rc
- language/np3_af_za/strings_af_za.rc
- language/np3_zh_cn/strings_zh_cn.rc
- language/np3_zh_tw/strings_zh_tw.rc
- minipath/License.txt
- minipath/src/version.h
- np3portableapp/Notepad3Portable/help.html
- src/Dialogs.c
- src/Notepad3.h
- src/Version.h
- src/crypto/extras/DecryptNotepad3.java
- test/test_files/StyleLexers/styleLexJAVA/DecryptNotepad3.java
- Correction of Rizonesoft's URL
> MUI - Commit before release build "Notepad3 6.24.1222.1 beta"

- scintilla/win32/ScintillaWin.cxx
The show count [1] of the mouse cursor, controlled by `ShowCursor()`, is thread-local and has an effect only when the cursor is above a window of the same thread. On the other hand, `GetCursorInfo()` reports the asynchronous state of the cursor, which may be outside the editor window and doesn't reflect the show count of our thread.
So, it is incorrect to manipulate the show count according to the result of `GetCursorInfo()`. This commit reverts relevant changes about `cursorIsHidden` in upstream Scintilla.
When the editor window loses focus but the cursor is not above it, the system does not send a `WM_MOUSELEAVE` notification. So we also have to recover the cursor state in `WM_KILLFOCUS`.
This closes https://github.com/rizonesoft/Notepad3/issues/5369
[1] …
> Recover cursor state when editor window loses focus

- Build/Themes/Dark.ini
- Build/Themes/Obsidian.ini
- Build/Themes/Sombra.ini
- Build/minipath.ini
- src/StyleLexers/styleLexCPP.c
> MUI - for "OpenCL",  add the "CL" extension in "C/C++ Source Code" Lexer

- src/Dialogs.c
- src/Edit.c
- src/Edit.h
- src/Helpers.c
- src/Notepad3.c
- src/Notepad3.h
- src/SciCall.h
> Adapt to new Scintilla API functions and bugfixing

- src/Dialogs.c
- src/Notepad3.c
- src/PathLib.c
- src/PathLib.h
- src/Styles.c
> Update Bars - check for changed filename always

- scintilla/call/ScintillaCall.cxx
- scintilla/doc/Lexer.txt
- scintilla/doc/ScintillaDoc.html
- scintilla/doc/ScintillaHistory.html
- scintilla/include/Scintilla.iface
- scintilla/include/ScintillaCall.h
- scintilla/include/ScintillaMessages.h
- scintilla/scripts/FileGenerator.py
- scintilla/src/CellBuffer.cxx
- scintilla/src/Document.h
- scintilla/src/EditModel.cxx
- scintilla/src/EditModel.h
- scintilla/src/EditView.cxx
- scintilla/src/Editor.cxx
- scintilla/src/Editor.h
- scintilla/src/PerLine.cxx
- scintilla/src/Platform.h
- scintilla/src/PositionCache.cxx
- scintilla/src/PositionCache.h
- scintilla/src/Selection.cxx
- scintilla/src/Selection.h
- scintilla/src/Style.cxx
- scintilla/src/ViewStyle.cxx
- scintilla/src/ViewStyle.h
- scintilla/win32/ListBox.cxx
- scintilla/win32/PlatWin.h
- scintilla/win32/Scintilla.vcxproj
- scintilla/win32/ScintillaWin.cxx
> update Scintilla, fix issue IME zoom

- language/np3_it_it/menu_it_it.rc
@rizonesoft 
Please check and merge . Thanks.
> Italian language update

- Build/Changes.txt
ref. issue #5465
ref. PR #5458
> Correction - MUI - Commit before release build "Notepad3 6.25.917.1 beta
